genMapHTMLTop<-function(outputFileHtmlCon, mapYear) {
  writeLines(paste0('<!DOCTYPE html>'), outputFileHtmlCon)
  writeLines(paste0('<html>'), outputFileHtmlCon)
  writeLines(paste0('<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">'), outputFileHtmlCon)
  writeLines(paste0("<!-- Global site tag (gtag.js) - Google Analytics -->"), outputFileHtmlCon)
  writeLines(paste0('  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-137783752-1"></script>'), outputFileHtmlCon)
  writeLines(paste0("  <script>"), outputFileHtmlCon)
  writeLines(paste0("  window.dataLayer = window.dataLayer || [];"), outputFileHtmlCon)
  writeLines(paste0("function gtag(){dataLayer.push(arguments);}"), outputFileHtmlCon)
  writeLines(paste0("gtag('js', new Date());"), outputFileHtmlCon)
  writeLines(paste0("gtag('config', 'UA-137783752-1');"), outputFileHtmlCon)
  writeLines(paste0("</script>"), outputFileHtmlCon)
  writeLines(paste0('<title>Ottawa Mass Transit Maps ',mapYear,'</title>'), outputFileHtmlCon)
  writeLines(paste0('<link href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css" rel="stylesheet" /><script src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script><script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>'), outputFileHtmlCon)
  writeLines(paste0('<style type="text/css">#my-map {'), outputFileHtmlCon)
  writeLines(paste0('  width:960px;'), outputFileHtmlCon)
  writeLines(paste0('  height:700px;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)
  writeLines(paste0('h1 {'), outputFileHtmlCon)
  writeLines(paste0('  color: #AA0000;'), outputFileHtmlCon)
  writeLines(paste0('  font-size: 24px;'), outputFileHtmlCon)
  writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)
  writeLines(paste0('h2 {'), outputFileHtmlCon)
  writeLines(paste0('  color: #000000;'), outputFileHtmlCon)
  writeLines(paste0('  font-size: 20px;'), outputFileHtmlCon)
  writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)
  writeLines(paste0('h3 {'), outputFileHtmlCon)
  writeLines(paste0('  color: #000000;'), outputFileHtmlCon)
  writeLines(paste0('  font-size: 16px;'), outputFileHtmlCon)
  writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)    
  writeLines(paste0('p {'), outputFileHtmlCon)
  writeLines(paste0('  color: #996600;'), outputFileHtmlCon)
  writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)
  writeLines(paste0('th {'), outputFileHtmlCon)
  writeLines(paste0('  text-align: right;'), outputFileHtmlCon)
  writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
  writeLines(paste0('  color: #663300;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)
  writeLines(paste0('td {'), outputFileHtmlCon)
  writeLines(paste0('  text-align: right;'), outputFileHtmlCon)
  writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
  writeLines(paste0('  color: #663300;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)
  writeLines(paste0('</style>'), outputFileHtmlCon)
  writeLines(paste0('</head>'), outputFileHtmlCon)
  writeLines(paste0('<body>'), outputFileHtmlCon)
  writeLines(paste0('  <p><a href="https://github.com/jeffblackadar/oc-transpo-maps/blob/master/oc_tips.md">Instructions</a>: Click on map features. Scroll down. | <a href="https://github.com/jeffblackadar/oc-transpo-maps/blob/master/oc_about.md">About the project</a> | * Draft work in progress *</p>'), outputFileHtmlCon)
  writeLines(paste0('  <div id="my-map"></div>'), outputFileHtmlCon)
  writeLines(paste0('    <script>'), outputFileHtmlCon)
  writeLines(paste0('    // This file was generated by this R program:  https://github.com/jeffblackadar/oc-transpo-maps/blob/master/oc_4_gen_html.r'), outputFileHtmlCon)
  writeLines(paste0('  var urbanExtentLayer;'), outputFileHtmlCon)
  writeLines(paste0('  var map;'), outputFileHtmlCon)
}

genMapHTMLMapTop<-function(outputFileHtmlCon) {
  writeLines("", outputFileHtmlCon)
  writeLines("      map = L.map('my-map')", outputFileHtmlCon)
  writeLines("      //.fitBounds(geojson.getBounds());", outputFileHtmlCon)
  writeLines("      //    .setView([0.0,-10.0], 2);", outputFileHtmlCon)
  writeLines("      basemap.addTo(map);", outputFileHtmlCon)
  writeLines("", outputFileHtmlCon)      
  writeLines("      // add legend control layers - global variable with (null, null) allows indiv basemaps and overlays to be added inside functions below", outputFileHtmlCon)
  writeLines("      var controlLayers = L.control.layers(null, null, {", outputFileHtmlCon)
  writeLines('        position: "topleft",', outputFileHtmlCon)
  writeLines("        collapsed: false // false = open by default", outputFileHtmlCon)
  writeLines("      }).addTo(map);", outputFileHtmlCon)
  writeLines("", outputFileHtmlCon)   
}
genHTMLUrbanExtent<-function(outputFileHtmlCon,urbanGrowthYear){
  writeLines(paste0("// Urban extent"), outputFileHtmlCon)
  writeLines(paste0("      $.ajax({"), outputFileHtmlCon)
  writeLines(paste0("        type: 'POST',"), outputFileHtmlCon)
  writeLines(paste0("        url: 'urban_growth_",urbanGrowthYear,".geojson',"), outputFileHtmlCon)
  writeLines(paste0("        dataType: 'json',"), outputFileHtmlCon)
  writeLines(paste0("        success: function(response) {"), outputFileHtmlCon)
  writeLines(paste0("          urbanExtentLayer = L.geoJson(response);"), outputFileHtmlCon)
  writeLines(paste0("          urbanExtentLayer.setStyle({"), outputFileHtmlCon)
  writeLines(paste0("            color: 'brown',"), outputFileHtmlCon)
  writeLines(paste0("            weight: 1"), outputFileHtmlCon)
  writeLines(paste0("          });"), outputFileHtmlCon)
  writeLines(paste0("          urbanExtentLayer.bindPopup('Urban extent ",urbanGrowthYear,".')"), outputFileHtmlCon)
  writeLines(paste0("          urbanExtentLayer.addTo(map);"), outputFileHtmlCon)
  writeLines(paste0("          controlLayers.addOverlay(urbanExtentLayer, '", '<span style=','"color:brown">',"Urban Extent ",urbanGrowthYear,"</span>');"), outputFileHtmlCon)
  writeLines(paste0("          map.fitBounds(urbanExtentLayer.getBounds());"), outputFileHtmlCon)
  writeLines(paste0("        }"), outputFileHtmlCon)
  writeLines(paste0("      });"), outputFileHtmlCon)
  writeLines(paste0(""), outputFileHtmlCon)
}

genHTMLPageLinks<-function(outputFileHtmlCon,pageLinks){
   writeLines(paste0("<h2>Links to maps of other years</h2>"), outputFileHtmlCon)
   writeLines(paste0("<p>",pageLinks,"</p>"), outputFileHtmlCon)
   writeLines(paste0("<hr><p>Observations may be sent to <a href='https://twitter.com/jeffblackadar'>@jeffblackadar</a> on Twitter.</p>"), outputFileHtmlCon)
}
library(RMariaDB)

# R needs a full path to find the settings file.
rmariadb.settingsfile<-"C:\\ProgramData\\MySQL\\MySQL Server 8.0\\oc_transpo_maps.cnf"

rmariadb.db<-"oc_transpo_maps"
routesDb<-dbConnect(RMariaDB::MariaDB(),default.file=rmariadb.settingsfile,group=rmariadb.db) 

# list the table. This confirms we connected to the database.
dbListTables(routesDb)


#Generate links
pageLinks="";
for (generateYear in 1929:2015){
  
  print(paste0("Making links for year ", generateYear))
  
  #There are 2 files for 1954, so do this twice for June and Dec.
  mapYear=generateYear
  output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE YEAR=",mapYear," ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
  #A kluge to use 1953, but worth it to avoid complexity
  if(generateYear==1953){
    mapYear="1954_June"    
    output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_June' ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
  }
  if(generateYear==1954){
    mapYear="1954_December"
    output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_December' ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
  }
  
  output_rs = dbSendQuery(routesDb,output_query)
  output_dbRows<-dbFetch(output_rs, 999999)
  if (nrow(output_dbRows)==0){
    dbClearResult(output_rs)
  } else {
    pageLinks<-paste0(pageLinks,"<a href='",mapYear,".html'>",mapYear,"</a> | ")
    dbClearResult(output_rs)
  }
}
#Add two extra page links
pageLinks<-paste0(pageLinks,"<a href='urbanextent.html'>Urban Extent 1925-2012</a> | ")




for (generateYear in 1929:2015){
  
  
  
  #There are 2 files for 1954, so do this twice for June and Dec.
  mapYear=generateYear
  output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE YEAR=",mapYear," ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
  #A kluge to use 1953, but worth it to avoid complexity
  if(generateYear==1953){
    mapYear="1954_June"    
    output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_June' ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
  }
  if(generateYear==1954){
    mapYear="1954_December"
    output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_December' ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
  }

  output_rs = dbSendQuery(routesDb,output_query)
  output_dbRows<-dbFetch(output_rs, 999999)
  if (nrow(output_dbRows)==0){
    print (paste0("Zero rows for ",mapYear))
    dbClearResult(output_rs)
    
  } else {
    print(paste0("Generating maps and geojson for year ", mapYear))  
    #which urban growth year to use?
    urbanGrowthYear=1925
    if(generateYear>=1929 & generateYear<1945){
      urbanGrowthYear=1925  
    } else {
      if(generateYear>=1945 & generateYear<1956){
        urbanGrowthYear=1945  
      } else {
        if(generateYear>=1956 & generateYear<1976){
          urbanGrowthYear=1956  
        } else {
          if(generateYear>=1976 & generateYear<1996){
            urbanGrowthYear=1976  
          } else {
            if(generateYear>=1996 & generateYear<2008){
              urbanGrowthYear=1996  
            } else {
              if(generateYear>=2008 & generateYear<2012){
                urbanGrowthYear=2008  
              } else {
                if(generateYear>=2012 & generateYear<2016){
                  urbanGrowthYear=2012  
                } else {
                  #This would be a problem.
                  urbanGrowthYear=1925              
                }
              }
            }
          }
        }
      }  
    }
    
    censusYear=0
    censusCMA_no=10
    if(generateYear>=1961 & generateYear<1971){
      censusYear=1961
      censusCMA_no=6
    } else {
      if(generateYear>=1971 & generateYear<1976){
        censusYear=1971  
        censusCMA_no=10
      } 
    }
    
    
    dbClearResult(output_rs)
    outputFileHtml <- paste0("C:\\a_orgs\\carleton\\hist3814\\R\\oc-transpo-maps-data\\output\\",mapYear,".html")
    outputFileHtmlCon<-file(outputFileHtml, open = "w")
    
    genMapHTMLTop(outputFileHtmlCon, mapYear)
      
    # writeLines(paste0('<!DOCTYPE html>'), outputFileHtmlCon)
    # writeLines(paste0('<html>'), outputFileHtmlCon)
    # writeLines(paste0('<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">'), outputFileHtmlCon)
    # writeLines(paste0("<!-- Global site tag (gtag.js) - Google Analytics -->"), outputFileHtmlCon)
    # writeLines(paste0('  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-137783752-1"></script>'), outputFileHtmlCon)
    # writeLines(paste0("  <script>"), outputFileHtmlCon)
    # writeLines(paste0("  window.dataLayer = window.dataLayer || [];"), outputFileHtmlCon)
    # writeLines(paste0("function gtag(){dataLayer.push(arguments);}"), outputFileHtmlCon)
    # writeLines(paste0("gtag('js', new Date());"), outputFileHtmlCon)
    # writeLines(paste0("gtag('config', 'UA-137783752-1');"), outputFileHtmlCon)
    # writeLines(paste0("</script>"), outputFileHtmlCon)
    #   
    # 
    # writeLines(paste0('<title>Ottawa Mass Transit Maps ',mapYear,'</title>'), outputFileHtmlCon)
    # writeLines(paste0('<link href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css" rel="stylesheet" /><script src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script><script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>'), outputFileHtmlCon)
    # writeLines(paste0('<style type="text/css">#my-map {'), outputFileHtmlCon)
    # writeLines(paste0('  width:960px;'), outputFileHtmlCon)
    # writeLines(paste0('  height:700px;'), outputFileHtmlCon)
    # writeLines(paste0('}'), outputFileHtmlCon)
    # writeLines(paste0('h1 {'), outputFileHtmlCon)
    # writeLines(paste0('  color: #AA0000;'), outputFileHtmlCon)
    # writeLines(paste0('  font-size: 24px;'), outputFileHtmlCon)
    # writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
    # writeLines(paste0('}'), outputFileHtmlCon)
    # writeLines(paste0('h2 {'), outputFileHtmlCon)
    # writeLines(paste0('  color: #000000;'), outputFileHtmlCon)
    # writeLines(paste0('  font-size: 20px;'), outputFileHtmlCon)
    # writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
    # writeLines(paste0('}'), outputFileHtmlCon)
    # writeLines(paste0('h3 {'), outputFileHtmlCon)
    # writeLines(paste0('  color: #000000;'), outputFileHtmlCon)
    # writeLines(paste0('  font-size: 16px;'), outputFileHtmlCon)
    # writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
    # writeLines(paste0('}'), outputFileHtmlCon)    
    # writeLines(paste0('p {'), outputFileHtmlCon)
    # writeLines(paste0('  color: #996600;'), outputFileHtmlCon)
    # writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
    # writeLines(paste0('}'), outputFileHtmlCon)
    # writeLines(paste0('th {'), outputFileHtmlCon)
    # writeLines(paste0('  text-align: right;'), outputFileHtmlCon)
    # writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
    # writeLines(paste0('  color: #663300;'), outputFileHtmlCon)
    # writeLines(paste0('}'), outputFileHtmlCon)
    # writeLines(paste0('td {'), outputFileHtmlCon)
    # writeLines(paste0('  text-align: right;'), outputFileHtmlCon)
    # writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
    # writeLines(paste0('  color: #663300;'), outputFileHtmlCon)
    # writeLines(paste0('}'), outputFileHtmlCon)
    # writeLines(paste0('</style>'), outputFileHtmlCon)
    # writeLines(paste0('</head>'), outputFileHtmlCon)
    # writeLines(paste0('<body>'), outputFileHtmlCon)
    # writeLines(paste0('  <p><a href="https://github.com/jeffblackadar/oc-transpo-maps/blob/master/oc_tips.md">Instructions</a>: Click on map features. Scroll down. | <a href="https://github.com/jeffblackadar/oc-transpo-maps/blob/master/oc_about.md">About the project</a> | * Draft work in progress *</p>'), outputFileHtmlCon)
    # writeLines(paste0('  <div id="my-map"></div>'), outputFileHtmlCon)
    # writeLines(paste0('    <script>'), outputFileHtmlCon)
    # writeLines(paste0('    // This file was generated by this R program:  https://github.com/jeffblackadar/oc-transpo-maps/blob/master/oc_4_gen_html.r'), outputFileHtmlCon)
    # writeLines(paste0('  var urbanExtentLayer;'), outputFileHtmlCon)
    # writeLines(paste0('  var map;'), outputFileHtmlCon)
    
    if(censusYear==1961 | censusYear==1971){
      writeLines(paste0("function colorValue(percent) {"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>100) {percent=100;}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent<0) {percent=0;}"), outputFileHtmlCon)
      writeLines(paste0("   hex = ((percent/100*255) >> 0).toString(16);"), outputFileHtmlCon)
      writeLines(paste0("   if(hex.length==1){"), outputFileHtmlCon)
      writeLines(paste0("      hex='0'+hex;"), outputFileHtmlCon)
      writeLines(paste0("   }"), outputFileHtmlCon)
      writeLines(paste0("   return hex;"), outputFileHtmlCon) 
      writeLines(paste0("}"), outputFileHtmlCon)
    
      #Thanks http://colorbrewer2.org/#type=sequential&scheme=RdPu&n=9
      writeLines(paste0("function chloroplethValue(percent) {"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>100) {percent=100;}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent<0) {percent=0;}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=40  & percent<100) {return '#49006a';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=30 & percent<40) {return '#7a0177';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=25 & percent<30) {return '#ae017e';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=20 & percent<25) {return '#dd3497';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=15 & percent<20) {return '#f768a1';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=10 & percent<15) {return '#fa9fb5';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=6 & percent<10) {return '#fcc5c0';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=3 & percent<6) {return '#fde0dd';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=0 & percent<3){return '#fff7f3';}"), outputFileHtmlCon)
      # ['#fff7f3','#fde0dd','#fcc5c0','#fa9fb5','#f768a1','#dd3497','#ae017e','#7a0177','#49006a']
      writeLines(paste0("   return '#fff7f3';"), outputFileHtmlCon) 
      writeLines(paste0("}"), outputFileHtmlCon)
    }
    
    writeLines(paste0(''), outputFileHtmlCon)
    # ['#fff7f3','#fde0dd','#fcc5c0','#fa9fb5','#f768a1','#dd3497','#ae017e','#7a0177','#49006a']
    
    writeLines(paste0('  window.onload = function() {'), outputFileHtmlCon)
    # Some early years have historical maps available. Load these as the basemap instead of OpenStreetMap
    if(generateYear>=1929 & generateYear<1939){
      writeLines(paste0("    var basemap = L.tileLayer('http://www.jeffblackadar.ca/oc-transpo/1927/{z}/{x}/{y}.png', {"), outputFileHtmlCon)
      writeLines(paste0("      attribution: '",'<a href="http://geo1.scholarsportal.info">Scholars Geoportal</a>',' | <a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">MacOdrum Library</a>',"'"), outputFileHtmlCon)
      writeLines(paste0("    });"), outputFileHtmlCon)
      basemapTitle="Topo. Map 1927"
    }else{
      if(generateYear>=1939 & generateYear<1948){
        writeLines(paste0("    var basemap = L.tileLayer('http://www.jeffblackadar.ca/oc-transpo/1939/{z}/{x}/{y}.png', {"), outputFileHtmlCon)
        writeLines(paste0("      attribution: '",'<a href="http://geo1.scholarsportal.info">Scholars Geoportal</a>',' | <a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">MacOdrum Library</a>',"'"), outputFileHtmlCon)
        writeLines(paste0("    });"), outputFileHtmlCon)
        basemapTitle="Topo. Map 1939"
      }else{
        if(generateYear>=1948 & generateYear<1953){
          writeLines(paste0("    var basemap = L.tileLayer('http://www.jeffblackadar.ca/oc-transpo/1948/{z}/{x}/{y}.png', {"), outputFileHtmlCon)
          writeLines(paste0("      attribution: '",'<a href="http://geo1.scholarsportal.info">Scholars Geoportal</a>',' | <a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">MacOdrum Library</a>',"'"), outputFileHtmlCon)
          writeLines(paste0("    });"), outputFileHtmlCon)
          basemapTitle="Topo. Map 1948"
        }else{
          writeLines(paste0("    var basemap = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {"), outputFileHtmlCon)
          writeLines(paste0("      attribution: '&copy; ",'<a href="http://osm.org/copyright">OpenStreetMap</a>',' contributors | <a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">MacOdrum Library</a>',"'"), outputFileHtmlCon)
          writeLines(paste0("    });"), outputFileHtmlCon)
          basemapTitle="Open Street Map Today"
        }
      }
    }
  
    genMapHTMLMapTop(outputFileHtmlCon)
    
    # writeLines(paste0(""), outputFileHtmlCon)
    # writeLines(paste0('//    $.getJSON("urban_growth_',urbanGrowthYear,'.geojson", function(data) {'), outputFileHtmlCon)
    # writeLines(paste0('//      geojson = L.geoJson(data, {'), outputFileHtmlCon)
    # writeLines(paste0("//      });"), outputFileHtmlCon)
    # 
    # writeLines("", outputFileHtmlCon)
    # writeLines("      map = L.map('my-map')", outputFileHtmlCon)
    # writeLines("//      .fitBounds(geojson.getBounds());", outputFileHtmlCon)
    # writeLines("      //    .setView([0.0,-10.0], 2);", outputFileHtmlCon)
    # writeLines("      basemap.addTo(map);", outputFileHtmlCon)
    # writeLines("", outputFileHtmlCon)      
    # writeLines("      // add legend control layers - global variable with (null, null) allows indiv basemaps and overlays to be added inside functions below", outputFileHtmlCon)
    # writeLines("      var controlLayers = L.control.layers(null, null, {", outputFileHtmlCon)
    # writeLines('        position: "topleft",', outputFileHtmlCon)
    # writeLines("        collapsed: false // false = open by default", outputFileHtmlCon)
    # writeLines("      }).addTo(map);", outputFileHtmlCon)
    # writeLines("", outputFileHtmlCon)   

    #routeTypes is used for the documentation below the map.
    routeTypes=""
    
    if(censusYear==1961 | censusYear==1971){
      writeLines(paste0("// Census"), outputFileHtmlCon)
      writeLines(paste0("   $.ajax({"), outputFileHtmlCon)
      writeLines(paste0("      type: 'POST',"), outputFileHtmlCon)
      writeLines(paste0("      url: '",censusYear,"_census_auto.geojson',"), outputFileHtmlCon)
      writeLines(paste0("      dataType: 'json',"), outputFileHtmlCon)
      writeLines(paste0("      success: function(response) {"), outputFileHtmlCon)
      writeLines(paste0("         censusAutoLayer = L.geoJson(response, {"), outputFileHtmlCon)
      writeLines(paste0("         "), outputFileHtmlCon)
      writeLines(paste0("         onEachFeature: function (feature, layer) {"), outputFileHtmlCon)
      writeLines(paste0("            "), outputFileHtmlCon)
      writeLines(paste0("            if(feature.properties.CMA_no==",censusCMA_no,"){"), outputFileHtmlCon)
      writeLines(paste0("               layer.bindPopup('<h3>Census ",censusYear," '+feature.properties.CMA_name+'</h3><table><tr><td>No Automobile: (*)</td><td>'+feature.properties.auto_none+'</td><td>'+feature.properties.auto_none_100+'%</td></tr><tr><td>One Automobile:</td><td>'+feature.properties.auto_one+'</td><td>'+feature.properties.auto_one_100+'%</td></tr><tr><td>Two Automobiles:</td><td>'+feature.properties.auto_two+'</td><td>'+feature.properties.auto_two_100+'%</td></tr><tr><td>CMA number:</td><td>'+feature.properties.CMA_no+'</td><td></td></tr><td>Census Tract:</td><td>'+feature.properties.CT+'</td><td></td></tr><table>');"), outputFileHtmlCon)
      writeLines(paste0("               layer.setStyle({"), outputFileHtmlCon)
      writeLines(paste0("                  color: 'white',"), outputFileHtmlCon)
      writeLines(paste0("                  fillColor: chloroplethValue(feature.properties.auto_none_100),"), outputFileHtmlCon)
      writeLines(paste0("                  weight: 0,"), outputFileHtmlCon)
      writeLines(paste0("                  opacity: 0,"), outputFileHtmlCon)
      writeLines(paste0("                  fillOpacity: .7"), outputFileHtmlCon)
      writeLines(paste0("                });"), outputFileHtmlCon)
      writeLines(paste0("             }"), outputFileHtmlCon)
      writeLines(paste0("             else{"), outputFileHtmlCon)
      writeLines(paste0("                layer.setStyle({"), outputFileHtmlCon)
      writeLines(paste0("                   color: 'white',"), outputFileHtmlCon)
      writeLines(paste0("                   weight: 0,"), outputFileHtmlCon)
      writeLines(paste0("                   opacity: 0"), outputFileHtmlCon)
      writeLines(paste0("                });"), outputFileHtmlCon)
      writeLines(paste0("             }"), outputFileHtmlCon)
      writeLines(paste0("          }"), outputFileHtmlCon)
      writeLines(paste0("       });"), outputFileHtmlCon)
      writeLines(paste0("          censusAutoLayer.addTo(map);"), outputFileHtmlCon)
      writeLines(paste0("          controlLayers.addOverlay(censusAutoLayer, '% No Automobile owned, ",censusYear," census');"), outputFileHtmlCon)
      writeLines(paste0("        }"), outputFileHtmlCon)
      writeLines(paste0("      });"), outputFileHtmlCon)
      writeLines(paste0(""), outputFileHtmlCon)
    }
    
    # rework this, like above
    if(generateYear==2929){
    writeLines(paste0("// Census"), outputFileHtmlCon)
    writeLines(paste0("   $.ajax({"), outputFileHtmlCon)
    writeLines(paste0("      type: 'POST',"), outputFileHtmlCon)
    writeLines(paste0("      url: 'http://jeffblackadar.ca/oc-transpo/1971_census_pop.geojson',"), outputFileHtmlCon)
    writeLines(paste0("      dataType: 'json',"), outputFileHtmlCon)
    writeLines(paste0("      success: function(response) {"), outputFileHtmlCon)
    writeLines(paste0("         censusPopLayer = L.geoJson(response, {"), outputFileHtmlCon)
    writeLines(paste0("         "), outputFileHtmlCon)
    writeLines(paste0("         onEachFeature: function (feature, layer) {"), outputFileHtmlCon)
    writeLines(paste0("            "), outputFileHtmlCon)
    writeLines(paste0("            if(feature.properties.CMAno==10){"), outputFileHtmlCon)
    writeLines(paste0("               layer.bindPopup('<h3>Census 1971 '+feature.properties.CMAname+'</h3><p>CMA number: '+feature.properties.CMAno+'</p><p>Population: '+feature.properties.totalPopulation+'</p>');"), outputFileHtmlCon)
    writeLines(paste0("                  layer.setStyle({"), outputFileHtmlCon)
    writeLines(paste0("                  color: 'yellow',"), outputFileHtmlCon)
    writeLines(paste0("                  weight: 1"), outputFileHtmlCon)
    writeLines(paste0("                });"), outputFileHtmlCon)
    writeLines(paste0("             }"), outputFileHtmlCon)
    writeLines(paste0("             else{"), outputFileHtmlCon)
    writeLines(paste0("                layer.setStyle({"), outputFileHtmlCon)
    writeLines(paste0("                   color: 'white',"), outputFileHtmlCon)
    writeLines(paste0("                   weight: 0,"), outputFileHtmlCon)
    writeLines(paste0("                   opacity: 0"), outputFileHtmlCon)
    writeLines(paste0("                });"), outputFileHtmlCon)
    writeLines(paste0("             }"), outputFileHtmlCon)
    writeLines(paste0("          }"), outputFileHtmlCon)
    writeLines(paste0("       });"), outputFileHtmlCon)
    writeLines(paste0("          censusPopLayer.addTo(map);"), outputFileHtmlCon)
    writeLines(paste0("          controlLayers.addOverlay(censusPopLayer, 'Population ",urbanGrowthYear,"');"), outputFileHtmlCon)
    writeLines(paste0("//          map.fitBounds(censusPopLayer.getBounds());"), outputFileHtmlCon)
    writeLines(paste0("        }"), outputFileHtmlCon)
    writeLines(paste0("      });"), outputFileHtmlCon)
    writeLines(paste0(""), outputFileHtmlCon)
    }
    
    genHTMLUrbanExtent(outputFileHtmlCon,urbanGrowthYear)    
    # writeLines(paste0("// Urban extent"), outputFileHtmlCon)
    # writeLines(paste0("      $.ajax({"), outputFileHtmlCon)
    # writeLines(paste0("        type: 'POST',"), outputFileHtmlCon)
    # writeLines(paste0("        url: 'urban_growth_",urbanGrowthYear,".geojson',"), outputFileHtmlCon)
    # writeLines(paste0("        dataType: 'json',"), outputFileHtmlCon)
    # writeLines(paste0("        success: function(response) {"), outputFileHtmlCon)
    # writeLines(paste0("          urbanExtentLayer = L.geoJson(response);"), outputFileHtmlCon)
    # writeLines(paste0("          urbanExtentLayer.setStyle({"), outputFileHtmlCon)
    # writeLines(paste0("            color: 'brown',"), outputFileHtmlCon)
    # writeLines(paste0("            weight: 1"), outputFileHtmlCon)
    # writeLines(paste0("          });"), outputFileHtmlCon)
    # writeLines(paste0("          urbanExtentLayer.bindPopup('Urban extent ",urbanGrowthYear,".')"), outputFileHtmlCon)
    # writeLines(paste0("          urbanExtentLayer.addTo(map);"), outputFileHtmlCon)
    # writeLines(paste0("          controlLayers.addOverlay(urbanExtentLayer, '", '<span style=','"color:brown">',"Urban Extent ",urbanGrowthYear,"</span>');"), outputFileHtmlCon)
    # writeLines(paste0("          map.fitBounds(urbanExtentLayer.getBounds());"), outputFileHtmlCon)
    # writeLines(paste0("        }"), outputFileHtmlCon)
    # writeLines(paste0("      });"), outputFileHtmlCon)
    # writeLines(paste0(""), outputFileHtmlCon)

    #Write a layer for each route type
    output_query_route_style<-paste0("SELECT tbl_route_maps.RTE_TYPE, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE, tbl_route_types.RTE_TYPE_MODE_CODE2, tbl_route_types.RTE_TYPE_MAP_COLOR FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE YEAR=",mapYear," GROUP BY RTE_TYPE ORDER BY RTE_TYPE DESC;")
    #A kluge to use 1953, but worth it to avoid complexity
    if(generateYear==1953){
      mapYear="1954_June"    
      #output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_June' ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
      output_query_route_style<-paste0("SELECT tbl_route_maps.RTE_TYPE, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE, tbl_route_types.RTE_TYPE_MODE_CODE2, tbl_route_types.RTE_TYPE_MAP_COLOR FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_June' GROUP BY RTE_TYPE ORDER BY RTE_TYPE DESC;")
    }
    if(generateYear==1954){
      mapYear="1954_December"
      #output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_December' ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
      output_query_route_style<-paste0("SELECT tbl_route_maps.RTE_TYPE, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE, tbl_route_types.RTE_TYPE_MODE_CODE2, tbl_route_types.RTE_TYPE_MAP_COLOR FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_December' GROUP BY RTE_TYPE ORDER BY RTE_TYPE DESC;")
    }
    output_rs_route_style = dbSendQuery(routesDb,output_query_route_style)
    output_dbRows_route_style<-dbFetch(output_rs_route_style, 999999)
    if (nrow(output_dbRows_route_style)==0){
      print (paste0("Zero rows for ",mapYear))
      dbClearResult(output_rs_route_style)
    } else {
      for (i_route_style in 1:nrow(output_dbRows_route_style)) {
        print(paste0("To map ", mapYear, ", adding: "))
        print(output_dbRows_route_style[i_route_style, 1])
        routeLayerName <- paste0(gsub("-","",gsub(" ","",output_dbRows_route_style[i_route_style, 1])),"Layer")
        
        writeLines(paste0(""), outputFileHtmlCon)
        writeLines(paste0("// layer for ",output_dbRows_route_style[i_route_style, 1]), outputFileHtmlCon)
        writeLines(paste0("var ",routeLayerName,";"), outputFileHtmlCon)
        
        writeLines(paste0("      $.ajax({"), outputFileHtmlCon)
        writeLines(paste0("        type: 'POST',"), outputFileHtmlCon)
        writeLines(paste0("        url: '",mapYear,"-",gsub(" ","-",output_dbRows_route_style[i_route_style, 1]),".geojson',"), outputFileHtmlCon)
        writeLines(paste0("        dataType: 'json',"), outputFileHtmlCon)
        writeLines(paste0("        success: function(response) {"), outputFileHtmlCon)
        writeLines(paste0("          ",routeLayerName," = L.geoJson(response, {"), outputFileHtmlCon)
        # Only need attribution once.
        #if(i_route_style ==1){
        #writeLines(paste0("      attribution: '",'<a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">Carleton University</a>'," ';"), outputFileHtmlCon)
        #}
        writeLines("             onEachFeature: function (feature, layer) {", outputFileHtmlCon)
        if(generateYear<=1948){
          writeLines(paste0("                 layer.bindPopup('<h3>Route Name: '+feature.properties.RTE_NAME+'</h3><p>'+feature.properties.RTE_TYPE+'</p><p>'+feature.properties.MODE+'</p>');"), outputFileHtmlCon)  
        }else{
          writeLines(paste0("                 layer.bindPopup('<h3>Route Number: '+feature.properties.RTE_NUM+'</h3><p>'+feature.properties.RTE_TYPE+'</p><p>'+feature.properties.MODE+'</p>');"), outputFileHtmlCon)  
        }
        
        writeLines(paste0("               }"), outputFileHtmlCon)
        writeLines(paste0("             });"), outputFileHtmlCon)
        writeLines(paste0("          ",routeLayerName,".setStyle({"), outputFileHtmlCon)
        writeLines(paste0("            color: '",output_dbRows_route_style[i_route_style, 6],"',"), outputFileHtmlCon)
        routeTypes <- paste0(routeTypes,"<span style=",'"color:',output_dbRows_route_style[i_route_style, 6],'"',">",output_dbRows_route_style[i_route_style, 1]," ___________</span><br>")
        writeLines(paste0("            weight: 2,"), outputFileHtmlCon)
        writeLines(paste0('            opacity: 1'), outputFileHtmlCon)
        writeLines(paste0("          });"), outputFileHtmlCon)
        writeLines(paste0("          ",routeLayerName,".addTo(map);"), outputFileHtmlCon)
        writeLines(paste0("          controlLayers.addOverlay(",routeLayerName,", '<span style=",'"color:',output_dbRows_route_style[i_route_style, 6],'"',">",output_dbRows_route_style[i_route_style, 1],"</span>');"), outputFileHtmlCon)
        writeLines(paste0("        }"), outputFileHtmlCon)
        writeLines(paste0("      });"), outputFileHtmlCon)
        writeLines(paste0(""), outputFileHtmlCon)
      }
      dbClearResult(output_rs_route_style)
    }

    writeLines(paste0("      controlLayers.addOverlay(basemap, '",basemapTitle,"');"), outputFileHtmlCon)
    writeLines(paste0("      "), outputFileHtmlCon)
    writeLines(paste0("//    });"), outputFileHtmlCon)
    writeLines(paste0("  };"), outputFileHtmlCon)
    writeLines(paste0("</script>"), outputFileHtmlCon)
    
    writeLines(paste0("<h1>Ottawa mass transit routes ",mapYear,"</h1>"), outputFileHtmlCon)
    writeLines(paste0('<p><a href="references.pdf">References used for this project.</a></p>'), outputFileHtmlCon)
    writeLines(paste0("<h2>Legend</h2>"), outputFileHtmlCon)
    writeLines(paste0("<h3>Route types</h3>"), outputFileHtmlCon)
    writeLines(paste0("<p>",routeTypes,"</p>"), outputFileHtmlCon)
    writeLines(paste0("<p>Each route can be clicked to view its route number and mode. Due to overlapping routes and layers, the route may be below other information on the map and not clickable. To bring it to the top of the map layers, click the layer twice in the control box at the top right portion of the map.</p>"), outputFileHtmlCon)
    writeLines(paste0("<h3>Base map</h3>"), outputFileHtmlCon)
    writeLines(paste0("<p>",basemapTitle," is the base map used to provide context for the mass transit routes.</p>"), outputFileHtmlCon)
    
    writeLines(paste0("<h3>Urban Extent</h3>"), outputFileHtmlCon)
    writeLines(paste0("<p>This layer shows the urban extent of the Ottawa-Gatineau region for the year ",urbanGrowthYear,". It is based on data compiled by the NCC and available at Carleton University's MacOdrum Library.</p>"), outputFileHtmlCon)
    if(censusYear==1961 | censusYear==1971){
      writeLines(paste0("<h3>Census Data</h3>"), outputFileHtmlCon)
      writeLines(paste0("<p>% population owning no automobile.</p>"), outputFileHtmlCon)
      writeLines(paste0("<table><tr>"), outputFileHtmlCon)
      writeLines(paste0("<script>"), outputFileHtmlCon)
      writeLines(paste0("for(counter=0;counter<=100;counter=counter+2){"), outputFileHtmlCon)
      
      writeLines(paste0("document.write('<td bgcolor='+chloroplethValue(counter)+'>&nbsp;&nbsp;</td>');"), outputFileHtmlCon)
      #writeLines(paste0("document.write('<td>&nbsp;&nbsp;</td>');"), outputFileHtmlCon)
      #writeLines(paste0("document.write(chloroplethValue(50));"), outputFileHtmlCon)
      writeLines(paste0(""), outputFileHtmlCon)
      writeLines(paste0("}"), outputFileHtmlCon)
      writeLines(paste0(""), outputFileHtmlCon)
      writeLines(paste0(""), outputFileHtmlCon)
      writeLines(paste0(""), outputFileHtmlCon)
      writeLines(paste0(""), outputFileHtmlCon)
      writeLines(paste0("</script>"), outputFileHtmlCon)
      writeLines(paste0("</tr>"), outputFileHtmlCon)
      writeLines(paste0("<tr>"), outputFileHtmlCon)
      for(tdCounter in 1:10){
      writeLines(paste0("<td colspan=5>",tdCounter*10,"%</td>"), outputFileHtmlCon)
      }
      writeLines(paste0("</tr>"), outputFileHtmlCon)
      writeLines(paste0("</table>"), outputFileHtmlCon)
    }
    
    genHTMLPageLinks(outputFileHtmlCon,pageLinks)
    # writeLines(paste0("<h2>Links to maps of other years</h2>"), outputFileHtmlCon)
    # writeLines(paste0("<p>",pageLinks,"</p>"), outputFileHtmlCon)
    # writeLines(paste0("<hr><p>Observations may be sent to <a href='https://twitter.com/jeffblackadar'>@jeffblackadar</a> on Twitter.</p>"), outputFileHtmlCon)
    
    writeLines(paste0("<h2>List of routes</h2>"), outputFileHtmlCon)
    writeLines(paste0("<table>"), outputFileHtmlCon)
    
    if(generateYear<=1948){
      writeLines(paste0("<tr><th>Map<br>line<br>colour</th><th>Route<br>name</th><th>Route type</th><th>Route mode</th></tr>"), outputFileHtmlCon)
    }else{
      writeLines(paste0("<tr><th>Map<br>line<br>colour</th><th>Route<br>number</th><th>Route type</th><th>Route mode</th></tr>"), outputFileHtmlCon)
    }
    output_query_route_style<-paste0("SELECT tbl_route_maps.RTE_TYPE, tbl_route_maps.RTE_NUM, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE, tbl_route_types.RTE_TYPE_MODE_CODE2, tbl_route_types.RTE_TYPE_MAP_COLOR FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE YEAR=",mapYear," ORDER BY RTE_NUM,RTE_TYPE;")
    #A kluge to use 1953, but worth it to avoid complexity
    if(generateYear==1953){
      mapYear="1954_June"    
      output_query_route_style<-paste0("SELECT tbl_route_maps.RTE_TYPE, tbl_route_maps.RTE_NUM, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE, tbl_route_types.RTE_TYPE_MODE_CODE2, tbl_route_types.RTE_TYPE_MAP_COLOR FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_June' ORDER BY RTE_NUM,RTE_TYPE;")
    }
    if(generateYear==1954){
      mapYear="1954_December"
      output_query_route_style<-paste0("SELECT tbl_route_maps.RTE_TYPE, tbl_route_maps.RTE_NUM, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE, tbl_route_types.RTE_TYPE_MODE_CODE2, tbl_route_types.RTE_TYPE_MAP_COLOR FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_December' ORDER BY RTE_NUM,RTE_TYPE;")
    }
    if(generateYear<=1948){
      output_query_route_style<-paste0("SELECT tbl_route_maps.RTE_TYPE, tbl_route_maps.RTE_NAME, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE, tbl_route_types.RTE_TYPE_MODE_CODE2, tbl_route_types.RTE_TYPE_MAP_COLOR FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE YEAR=",mapYear," ORDER BY RTE_NUM,RTE_TYPE;")
    }
    print(output_query_route_style)
    output_rs_route_style = dbSendQuery(routesDb,output_query_route_style)
    output_dbRows_route_style<-dbFetch(output_rs_route_style, 999999)
    if (nrow(output_dbRows_route_style)==0){
      print (paste0("Zero rows for ",mapYear))
      dbClearResult(output_rs_route_style)
    } else {
      for (i_route_style in 1:nrow(output_dbRows_route_style)) {
        #print(paste0("To map ", mapYear, " adding "))
        #print(output_dbRows_route_style[i_route_style, 1])
        routeLayerName <- paste0(gsub("-","",gsub(" ","",output_dbRows_route_style[i_route_style, 1])),"Layer")
        writeLines(paste0("<tr>"), outputFileHtmlCon)
        writeLines(paste0("<td bgcolor='",output_dbRows_route_style[i_route_style, 7],"'>&nbsp;&nbsp;&nbsp;</td>","<td>",output_dbRows_route_style[i_route_style, 2],"</td>","<td>",output_dbRows_route_style[i_route_style, 1],"</td>","<td>",output_dbRows_route_style[i_route_style, 4],"</td>"), outputFileHtmlCon)
        writeLines(paste0("</tr>"), outputFileHtmlCon)
      }
      dbClearResult(output_rs_route_style)
    }
    writeLines(paste0("</table>"), outputFileHtmlCon)
    writeLines(paste0("</body>"), outputFileHtmlCon)
    writeLines(paste0("</html>"), outputFileHtmlCon)
    close(outputFileHtmlCon)
  }
}
dbDisconnect(routesDb)


outputFileHtml <- paste0("C:\\a_orgs\\carleton\\hist3814\\R\\oc-transpo-maps-data\\output\\urbanextent.html")
outputFileHtmlCon<-file(outputFileHtml, open = "w")
genMapHTMLTop(outputFileHtmlCon, "Urban extent 1929-2015")
writeLines(paste0('  window.onload = function() {'), outputFileHtmlCon)
writeLines(paste0("    var basemap = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {"), outputFileHtmlCon)
writeLines(paste0("      attribution: '&copy; ",'<a href="http://osm.org/copyright">OpenStreetMap</a>',' contributors | <a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">MacOdrum Library</a>',"'"), outputFileHtmlCon)
writeLines(paste0("    });"), outputFileHtmlCon)
basemapTitle="Open Street Map Today"

genMapHTMLMapTop(outputFileHtmlCon)
genHTMLUrbanExtent(outputFileHtmlCon,1925)
genHTMLUrbanExtent(outputFileHtmlCon,1945)
genHTMLUrbanExtent(outputFileHtmlCon,1956)
genHTMLUrbanExtent(outputFileHtmlCon,1976)
genHTMLUrbanExtent(outputFileHtmlCon,1996)
genHTMLUrbanExtent(outputFileHtmlCon,2008)
genHTMLUrbanExtent(outputFileHtmlCon,2012)
writeLines(paste0("      controlLayers.addOverlay(basemap, '",basemapTitle,"');"), outputFileHtmlCon)
writeLines(paste0("      "), outputFileHtmlCon)
writeLines(paste0("  };"), outputFileHtmlCon)

writeLines(paste0("var controlChoices=document.getElementsByClassName('leaflet-control-layers-selector');"), outputFileHtmlCon)
writeLines(paste0("var animLayer=0;"), outputFileHtmlCon)

writeLines(paste0("// The years of urban growth data and their order."), outputFileHtmlCon)
writeLines(paste0("var urbanExtentYears = ["), outputFileHtmlCon)
writeLines(paste0("[1925, 1],"), outputFileHtmlCon)
writeLines(paste0("[1945, 2],"), outputFileHtmlCon)
writeLines(paste0("[1956, 3],"), outputFileHtmlCon)
writeLines(paste0("[1976, 4],"), outputFileHtmlCon)
writeLines(paste0("[1996, 5],"), outputFileHtmlCon)
writeLines(paste0("[2008, 6],"), outputFileHtmlCon)
writeLines(paste0("[2012, 7]"), outputFileHtmlCon)
writeLines(paste0("];"), outputFileHtmlCon)
writeLines(paste0("// The years of urban growth data may be out of order on the Leaflet control. "), outputFileHtmlCon)
writeLines(paste0("// Loop through the control, see where each year is and set the year's order in the list."), outputFileHtmlCon)
#writeLines(paste0("for(cc2 = 1;cc2<controlChoices.length;cc2=cc2+1){"), outputFileHtmlCon)
#writeLines(paste0("   for(cc = 1;cc<controlChoices.length;cc=cc+1){"), outputFileHtmlCon)
writeLines(paste0("function checkOrder(){"), outputFileHtmlCon)
writeLines(paste0("   controlChoices=document.getElementsByClassName('leaflet-control-layers-selector');"), outputFileHtmlCon)
writeLines(paste0("   for(cc2 = 0;cc2<urbanExtentYears.length;cc2=cc2+1){"), outputFileHtmlCon)
writeLines(paste0("      ue='Urban Extent '+urbanExtentYears[cc2][0];"), outputFileHtmlCon)
writeLines(paste0("      ue=ue.trim();"), outputFileHtmlCon)
writeLines(paste0("      for(cc = 1;cc<controlChoices.length;cc=cc+1){"), outputFileHtmlCon)
writeLines(paste0("         cchoice=controlChoices[cc].labels[0].innerText;"), outputFileHtmlCon)
writeLines(paste0("         cchoice=cchoice.trim();"), outputFileHtmlCon)
#writeLines(paste0('         document.write(ue+"----"+cchoice);'), outputFileHtmlCon)
writeLines(paste0('         if(ue===cchoice){'), outputFileHtmlCon)
writeLines(paste0("            urbanExtentYears[cc2][1]=cc;"), outputFileHtmlCon)
writeLines(paste0("            cc=controlChoices.length;"), outputFileHtmlCon)
writeLines(paste0("         }"), outputFileHtmlCon)
writeLines(paste0("      }"), outputFileHtmlCon)
writeLines(paste0("   }"), outputFileHtmlCon)
writeLines(paste0("}"), outputFileHtmlCon)

writeLines(paste0("// unChecks a choice if it is checked."), outputFileHtmlCon)
writeLines(paste0("function unClickChoice(checkBoxChoice){"), outputFileHtmlCon)
writeLines(paste0("   if(checkBoxChoice.checked==true){"), outputFileHtmlCon)
writeLines(paste0("      checkBoxChoice.click();"), outputFileHtmlCon)
writeLines(paste0("   }"), outputFileHtmlCon)
writeLines(paste0("}"), outputFileHtmlCon)
writeLines(paste0("// checks a choice if it is unchecked."), outputFileHtmlCon)
writeLines(paste0("function clickChoice(checkBoxChoice){"), outputFileHtmlCon)
writeLines(paste0("   if(checkBoxChoice.checked==false){"), outputFileHtmlCon)
writeLines(paste0("      checkBoxChoice.click();"), outputFileHtmlCon)
writeLines(paste0("   }"), outputFileHtmlCon)
writeLines(paste0("}"), outputFileHtmlCon)
writeLines(paste0("// unchecks all choices in the Leaflet control  "), outputFileHtmlCon)
writeLines(paste0("function unClickAll(){"), outputFileHtmlCon)
writeLines(paste0("   for(cc = 1;cc<controlChoices.length;cc=cc+1){"), outputFileHtmlCon)
writeLines(paste0("      unClickChoice(controlChoices[cc]);"), outputFileHtmlCon)
writeLines(paste0("   }"), outputFileHtmlCon)
writeLines(paste0("}"), outputFileHtmlCon)
writeLines(paste0("// checks all choices in the Leaflet control"), outputFileHtmlCon)
writeLines(paste0("function clickAll(){"), outputFileHtmlCon)
writeLines(paste0("   for(cc = 1;cc<controlChoices.length;cc=cc+1){"), outputFileHtmlCon)
writeLines(paste0("      clickChoice(controlChoices[cc]);"), outputFileHtmlCon)
writeLines(paste0("   }"), outputFileHtmlCon)
writeLines(paste0("}"), outputFileHtmlCon)  
writeLines(paste0("function stepAnimate(forward){"), outputFileHtmlCon)
writeLines(paste0("   controlChoices=document.getElementsByClassName('leaflet-control-layers-selector');"), outputFileHtmlCon)
writeLines(paste0("   unClickAll();"), outputFileHtmlCon)
writeLines(paste0("   checkOrder();"), outputFileHtmlCon)
writeLines(paste0("   animLayer=animLayer+forward;"), outputFileHtmlCon)	
writeLines(paste0("   if(animLayer>7){animLayer=1;}"), outputFileHtmlCon)
writeLines(paste0("   if(animLayer<1){animLayer=7;}"), outputFileHtmlCon)
writeLines(paste0("   clickChoice(controlChoices[urbanExtentYears[animLayer-1][1]]);"), outputFileHtmlCon)

writeLines(paste0("}"), outputFileHtmlCon)
writeLines(paste0("</script>"), outputFileHtmlCon)
writeLines(paste0("</table>"), outputFileHtmlCon)
writeLines(paste0('<input type="button" onClick="stepAnimate(1);" value="Animation - Forward in time.">'), outputFileHtmlCon)
writeLines(paste0('<input type="button" onClick="stepAnimate(-1);" value="Animation - Backward in time.">'), outputFileHtmlCon)
writeLines(paste0('<input type="button" onClick="unClickAll();" value="un-check all">'), outputFileHtmlCon)
writeLines(paste0('<input type="button" onClick="clickAll();" value="check all">'), outputFileHtmlCon)

genHTMLPageLinks(outputFileHtmlCon,pageLinks)

writeLines(paste0("</body>"), outputFileHtmlCon)
writeLines(paste0("</html>"), outputFileHtmlCon)
close(outputFileHtmlCon)
