genMapHTMLTop<-function(outputFileHtmlCon, mapYear) {
  writeLines(paste0('<!DOCTYPE html>'), outputFileHtmlCon)
  writeLines(paste0('<html>'), outputFileHtmlCon)
  writeLines(paste0('<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">'), outputFileHtmlCon)
  writeLines(paste0("<!-- Global site tag (gtag.js) - Google Analytics -->"), outputFileHtmlCon)
  writeLines(paste0('  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-137783752-1"></script>'), outputFileHtmlCon)
  writeLines(paste0("  <script>"), outputFileHtmlCon)
  writeLines(paste0("  window.dataLayer = window.dataLayer || [];"), outputFileHtmlCon)
  writeLines(paste0("function gtag(){dataLayer.push(arguments);}"), outputFileHtmlCon)
  writeLines(paste0("gtag('js', new Date());"), outputFileHtmlCon)
  writeLines(paste0("gtag('config', 'UA-137783752-1');"), outputFileHtmlCon)
  writeLines(paste0("</script>"), outputFileHtmlCon)
  writeLines(paste0('<title>',genPageTitle(mapYear),'</title>'), outputFileHtmlCon)
  writeLines(paste0('<link href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css" rel="stylesheet" /><script src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script><script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>'), outputFileHtmlCon)
  writeLines(paste0('<style type="text/css">#my-map {'), outputFileHtmlCon)
  writeLines(paste0('  width:960px;'), outputFileHtmlCon)
  writeLines(paste0('  height:700px;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)
  writeLines(paste0('h1 {'), outputFileHtmlCon)
  writeLines(paste0('  color: #AA0000;'), outputFileHtmlCon)
  writeLines(paste0('  font-size: 24px;'), outputFileHtmlCon)
  writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)
  writeLines(paste0('h2 {'), outputFileHtmlCon)
  writeLines(paste0('  color: #000000;'), outputFileHtmlCon)
  writeLines(paste0('  font-size: 20px;'), outputFileHtmlCon)
  writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)
  writeLines(paste0('h3 {'), outputFileHtmlCon)
  writeLines(paste0('  color: #000000;'), outputFileHtmlCon)
  writeLines(paste0('  font-size: 16px;'), outputFileHtmlCon)
  writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)    
  writeLines(paste0('p {'), outputFileHtmlCon)
  writeLines(paste0('  color: #996600;'), outputFileHtmlCon)
  writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)
  writeLines(paste0('li {'), outputFileHtmlCon)
  writeLines(paste0('  color: #996600;'), outputFileHtmlCon)
  writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)  
  writeLines(paste0('th {'), outputFileHtmlCon)
  writeLines(paste0('  text-align: right;'), outputFileHtmlCon)
  writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
  writeLines(paste0('  color: #663300;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)
  writeLines(paste0('td {'), outputFileHtmlCon)
  writeLines(paste0('  text-align: right;'), outputFileHtmlCon)
  writeLines(paste0('  font-family: verdana;'), outputFileHtmlCon)
  writeLines(paste0('  color: #663300;'), outputFileHtmlCon)
  writeLines(paste0('}'), outputFileHtmlCon)
  writeLines(paste0('</style>'), outputFileHtmlCon)
  writeLines(paste0('</head>'), outputFileHtmlCon)
  writeLines(paste0('<body>'), outputFileHtmlCon)
}

genMapHTMLScriptTop<-function(outputFileHtmlCon, mapYear) {  
  writeLines(paste0('  <p>',genPageTitle(mapYear),' | <a href="https://github.com/jeffblackadar/oc-transpo-maps/blob/master/oc_tips.md">Usage tips</a>. </p>'), outputFileHtmlCon)
  writeLines(paste0('  <div id="my-map"></div>'), outputFileHtmlCon)
  writeLines(paste0('    <script>'), outputFileHtmlCon)
  writeLines(paste0('    // This file was generated by this R program:  https://github.com/jeffblackadar/oc-transpo-maps/blob/master/oc_4_gen_html.r'), outputFileHtmlCon)
  writeLines(paste0('  var urbanExtentLayer;'), outputFileHtmlCon)
  writeLines(paste0('  var map;'), outputFileHtmlCon)
}

genMapHTMLMapTop<-function(outputFileHtmlCon) {
  writeLines("", outputFileHtmlCon)
  writeLines("      map = L.map('my-map')", outputFileHtmlCon)
  writeLines("      //.fitBounds(geojson.getBounds());", outputFileHtmlCon)
  writeLines("      //    .setView([0.0,-10.0], 2);", outputFileHtmlCon)
  writeLines("      basemap.addTo(map);", outputFileHtmlCon)
  writeLines("", outputFileHtmlCon)      
  writeLines("      // add legend control layers - global variable with (null, null) allows indiv basemaps and overlays to be added inside functions below", outputFileHtmlCon)
  writeLines("      var controlLayers = L.control.layers(null, null, {", outputFileHtmlCon)
  writeLines('        position: "topleft",', outputFileHtmlCon)
  writeLines("        collapsed: false // false = open by default", outputFileHtmlCon)
  writeLines("      }).addTo(map);", outputFileHtmlCon)
  writeLines("", outputFileHtmlCon)   
}
genHTMLUrbanExtent<-function(outputFileHtmlCon,urbanGrowthYear){
  writeLines(paste0("// Urban extent"), outputFileHtmlCon)
  writeLines(paste0("      $.ajax({"), outputFileHtmlCon)
  writeLines(paste0("        type: 'POST',"), outputFileHtmlCon)
  writeLines(paste0("        url: 'urban_growth_",urbanGrowthYear,".geojson',"), outputFileHtmlCon)
  writeLines(paste0("        dataType: 'json',"), outputFileHtmlCon)
  writeLines(paste0("        success: function(response) {"), outputFileHtmlCon)
  writeLines(paste0("          urbanExtentLayer = L.geoJson(response);"), outputFileHtmlCon)
  writeLines(paste0("          urbanExtentLayer.setStyle({"), outputFileHtmlCon)
  writeLines(paste0("            color: 'brown',"), outputFileHtmlCon)
  writeLines(paste0("            weight: 1"), outputFileHtmlCon)
  writeLines(paste0("          });"), outputFileHtmlCon)
  writeLines(paste0("          urbanExtentLayer.bindPopup('Urban extent ",urbanGrowthYear,".')"), outputFileHtmlCon)
  writeLines(paste0("          urbanExtentLayer.addTo(map);"), outputFileHtmlCon)
  writeLines(paste0("          controlLayers.addOverlay(urbanExtentLayer, '", '<span style=','"color:brown">',"Urban Extent ",urbanGrowthYear,"</span>');"), outputFileHtmlCon)
  writeLines(paste0("          map.fitBounds(urbanExtentLayer.getBounds());"), outputFileHtmlCon)
  writeLines(paste0("        }"), outputFileHtmlCon)
  writeLines(paste0("      });"), outputFileHtmlCon)
  writeLines(paste0(""), outputFileHtmlCon)
}

genPageTitle<-function(mapYear){
  genPageTitle<-""
  if(mapYear>=1929 & mapYear<1950){
    genPageTitle<-paste0('Ottawa Electric Railway Company Mass Transit Map ',mapYear)
  }
  if(mapYear>=1950 & mapYear<1973){
    genPageTitle<-paste0('Ottawa Transportation Commission Mass Transit Map ',mapYear)
  }
  if(mapYear>=1973){
    genPageTitle<-paste0('OC Transpo Mass Transit Map ',mapYear)
  }
  return(genPageTitle)
}

genHTMLRailOnly<-function(outputFileHtmlCon,railYear){
  #print(paste0("To map for ", railYear, ", adding: "))
  #print(output_dbRows_route_style[i_route_style, 1])
  routeLayerName <- paste0("RailOnly",railYear, "Layer")
  
  writeLines(paste0(""), outputFileHtmlCon)
  writeLines(paste0("// layer for ",routeLayerName), outputFileHtmlCon)
  writeLines(paste0("var ",routeLayerName,";"), outputFileHtmlCon)
  
  writeLines(paste0("      $.ajax({"), outputFileHtmlCon)
  writeLines(paste0("        type: 'POST',"), outputFileHtmlCon)
  #There are 2 files for 1954 - use the December one
  if(railYear==1954){
     writeLines(paste0("        url: '",railYear,"_December_rail_only_map.geojson',"), outputFileHtmlCon)
  }else{
     writeLines(paste0("        url: '",railYear,"_rail_only_map.geojson',"), outputFileHtmlCon)
  }
  writeLines(paste0("        dataType: 'json',"), outputFileHtmlCon)
  writeLines(paste0("        success: function(response) {"), outputFileHtmlCon)
  writeLines(paste0("          ",routeLayerName," = L.geoJson(response, {"), outputFileHtmlCon)
  
  writeLines(paste0("             onEachFeature: function (feature, layer) {"), outputFileHtmlCon)
  if(railYear<=1948){
    writeLines(paste0("                 layer.bindPopup('<h3>Route Name: '+feature.properties.RTE_NAME+'</h3><p>'+feature.properties.RTE_TYPE+'</p><p>'+feature.properties.MODE+'</p>');"), outputFileHtmlCon)  
  }else{
    writeLines(paste0("                 layer.bindPopup('<h3>Route Number: '+feature.properties.RTE_NUM+'</h3><p>'+feature.properties.RTE_TYPE+'</p><p>'+feature.properties.MODE+'</p>');"), outputFileHtmlCon)  
  }
  
  writeLines(paste0("               }"), outputFileHtmlCon)
  writeLines(paste0("             });"), outputFileHtmlCon)
  writeLines(paste0("          ",routeLayerName,".setStyle({"), outputFileHtmlCon)
  writeLines(paste0("            color: 'purple',"), outputFileHtmlCon)
  writeLines(paste0("            weight: 2,"), outputFileHtmlCon)
  writeLines(paste0('            opacity: 1'), outputFileHtmlCon)
  writeLines(paste0("          });"), outputFileHtmlCon)
  writeLines(paste0("          ",routeLayerName,".addTo(map);"), outputFileHtmlCon)
  #Street cars ended in 1959
  if(railYear<=1959){
    writeLines(paste0("          controlLayers.addOverlay(",routeLayerName,", '<span style=",'"color: purple"',">",railYear," Street Cars only</span>');"), outputFileHtmlCon)
  }else{
     writeLines(paste0("          controlLayers.addOverlay(",routeLayerName,", '<span style=",'"color: purple"',">",railYear," Train only</span>');"), outputFileHtmlCon)
  }
  writeLines(paste0("        }"), outputFileHtmlCon)
  writeLines(paste0("      });"), outputFileHtmlCon)
  writeLines(paste0(""), outputFileHtmlCon)
  
}


genHTMLMajorChanges<-function(outputFileHtmlCon,changeYear){
  #print(paste0("To map ", changeYear, ", adding: "))
  
  routeLayerName <- paste0("layer",changeYear)
  
  writeLines(paste0(""), outputFileHtmlCon)
  writeLines(paste0("// layer for ",routeLayerName), outputFileHtmlCon)
  writeLines(paste0("var ",routeLayerName,";"), outputFileHtmlCon)
  
  writeLines(paste0("      $.ajax({"), outputFileHtmlCon)
  writeLines(paste0("        type: 'POST',"), outputFileHtmlCon)
  #There are 2 files for 1954 - use the December one
  if(changeYear==1954){
    writeLines(paste0("        url: '",changeYear,"_December.geojson',"), outputFileHtmlCon)
  }else{
    writeLines(paste0("        url: '",changeYear,".geojson',"), outputFileHtmlCon)
  }
  writeLines(paste0("        dataType: 'json',"), outputFileHtmlCon)
  writeLines(paste0("        success: function(response) {"), outputFileHtmlCon)
  writeLines(paste0("          ",routeLayerName," = L.geoJson(response, {"), outputFileHtmlCon)
  
  #writeLines(paste0("             onEachFeature: function (feature, layer) {"), outputFileHtmlCon)
  #if(changeYear<=1948){
  #  writeLines(paste0("                 layer.bindPopup('<h3>Route Name: '+feature.properties.RTE_NAME+'</h3><p>'+feature.properties.RTE_TYPE+'</p><p>'+feature.properties.MODE+'</p>');"), outputFileHtmlCon)  
  #}else{
  #  writeLines(paste0("                 layer.bindPopup('<h3>Route Number: '+feature.properties.RTE_NUM+'</h3><p>'+feature.properties.RTE_TYPE+'</p><p>'+feature.properties.MODE+'</p>');"), outputFileHtmlCon)  
  #}
  #
  #writeLines(paste0("               }"), outputFileHtmlCon)
  writeLines(paste0("             });"), outputFileHtmlCon)
  writeLines(paste0("          ",routeLayerName,".setStyle({"), outputFileHtmlCon)
  writeLines(paste0("            color: 'blue',"), outputFileHtmlCon)
  writeLines(paste0("            weight: 3,"), outputFileHtmlCon)
  writeLines(paste0('            opacity: 1'), outputFileHtmlCon)
  writeLines(paste0("          });"), outputFileHtmlCon)
  writeLines(paste0("          ",routeLayerName,".addTo(map);"), outputFileHtmlCon)
  writeLines(paste0("          controlLayers.addOverlay(",routeLayerName,", '<span style=",'"color: blue"',">",changeYear," All Routes</span>');"), outputFileHtmlCon)
  writeLines(paste0("        }"), outputFileHtmlCon)
  writeLines(paste0("      });"), outputFileHtmlCon)
  writeLines(paste0(""), outputFileHtmlCon)
}




genHTMLPageLinks<-function(outputFileHtmlCon,pageLinks){
   writeLines(paste0("<h2>Links to maps by year</h2>"), outputFileHtmlCon)
   writeLines(paste0("<p>",pageLinks,"</p>"), outputFileHtmlCon)
   writeLines(paste0("<hr><p>Observations may be sent to <a href='https://twitter.com/jeffblackadar'>@jeffblackadar</a> on Twitter.</p>"), outputFileHtmlCon)
}

genHTMLLeafletClickChoiceFunctions<-function(outputFileHtmlCon,pageLinks){
  writeLines(paste0("// unChecks a choice if it is checked."), outputFileHtmlCon)
  writeLines(paste0("function unClickChoice(checkBoxChoice){"), outputFileHtmlCon)
  writeLines(paste0("   if(checkBoxChoice.checked==true){"), outputFileHtmlCon)
  writeLines(paste0("      checkBoxChoice.click();"), outputFileHtmlCon)
  writeLines(paste0("   }"), outputFileHtmlCon)
  writeLines(paste0("}"), outputFileHtmlCon)
  writeLines(paste0("// checks a choice if it is unchecked."), outputFileHtmlCon)
  writeLines(paste0("function clickChoice(checkBoxChoice){"), outputFileHtmlCon)
  writeLines(paste0("   if(checkBoxChoice.checked==false){"), outputFileHtmlCon)
  writeLines(paste0("      checkBoxChoice.click();"), outputFileHtmlCon)
  writeLines(paste0("   }"), outputFileHtmlCon)
  writeLines(paste0("}"), outputFileHtmlCon)
  writeLines(paste0("// unchecks all choices in the Leaflet control  "), outputFileHtmlCon)
  writeLines(paste0("function unClickAll(){"), outputFileHtmlCon)
  writeLines(paste0("   for(cc = 1;cc<controlChoices.length;cc=cc+1){"), outputFileHtmlCon)
  writeLines(paste0("      unClickChoice(controlChoices[cc]);"), outputFileHtmlCon)
  writeLines(paste0("   }"), outputFileHtmlCon)
  writeLines(paste0("}"), outputFileHtmlCon)
  writeLines(paste0("// checks all choices in the Leaflet control"), outputFileHtmlCon)
  writeLines(paste0("function clickAll(){"), outputFileHtmlCon)
  writeLines(paste0("   for(cc = 1;cc<controlChoices.length;cc=cc+1){"), outputFileHtmlCon)
  writeLines(paste0("      clickChoice(controlChoices[cc]);"), outputFileHtmlCon)
  writeLines(paste0("   }"), outputFileHtmlCon)
  writeLines(paste0("}"), outputFileHtmlCon)
}

genHTMLFootnotes<-function(outputFileHtmlCon,generateYear){
  
  writeLines(paste0('<p><a name="roctranspogis">1. OC Transpo, OC Transpo Transit Routes 1929-2015, ESRI Shapefiles, Ottawa, Ontario: MacOdrum Library, Carleton University, August 29, 2018.</a> <a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes</a>.</p>'), outputFileHtmlCon)
  writeLines(paste0('<p><a name="rnccue">2. National Capital Commission, Urban Growth (National Capital Commission) - 1810-2012 Intermittent, ESRI Shapefiles, Ottawa, Ontario: MacOdrum Library, Carleton University, August 29, 2018.</a></p>'), outputFileHtmlCon)
  
  #National Defence Map references
  if(generateYear>=1929 & generateYear<1939){
    writeLines(paste0('<p><a name="rmap1927">3. Geographical Section, General Staff, Department of National Defence, "Ottawa, Ontario. 1:63,360. Map Sheet 031G05, [Ed. 8], 1927," Map, Scholars Portal, Accessed April 13, 2019.</a> <a href="https://scholarsportal.info/">https://scholarsportal.info/</a></p>'), outputFileHtmlCon)
  }else{
    if(generateYear>=1939 & generateYear<1948){
      writeLines(paste0('<p><a name="rmap1939">4. Geographical Section, General Staff, Department of National Defence, "Ottawa- Gatineau District, Ontario. 1:63,360. Map Sheet 031G05-G12, [Ed. 2], 1939," Map, Scholars Portal, Accessed April 13, 2019.</a> <a href="https://scholarsportal.info/">https://scholarsportal.info/</a></p>'), outputFileHtmlCon)
    }else{
      if(generateYear>=1948 & generateYear<1953){
        writeLines(paste0('<p><a name="rmap1948">5. Geographical Section, General Staff, Department of National Defence, "Ottawa, Ontario. 1:63,360. Map Sheet 031G05, [Ed. 17], Gridded, 1948," Map, Scholars Portal, Accessed April 13, 2019.</a> <a href="https://scholarsportal.info/">https://scholarsportal.info/</a></p>'), outputFileHtmlCon)
      } else {
        writeLines(paste0('<p><a name="rmaposm">8. &copy; OpenStreetMap contributors, "OpenStreetMap Ottawa," Map, <i>OpenStreetMap.</i> OpenStreetMap Foundation (OSMF), Accessed April 14, 2019.</a> <a href="https://www.openstreetmap.org">https://www.openstreetmap.org</a>.</p>'), outputFileHtmlCon)
      }
    }
  }
  
  #Census references
  if(generateYear>=1961 & generateYear<1971){
    writeLines(paste0('<p><a name="rcensus1961">6. Statistics Canada, "Canadian 1961 Census Profile (Census Tract Level)," Canadian Census Analyser, Toronto:Ontario. Accessed April 13, 2019.</a> <a href="http://dc1.chass.utoronto.ca/census/index.html">http://dc1.chass.utoronto.ca/census/index.html</a></p>'), outputFileHtmlCon) 
  } else {
    if(generateYear>=1971 & generateYear<1976){
      writeLines(paste0('<p><a name="rcensus1971">7. Statistics Canada, "Canadian 1971 Census Profile (Census Tract Level)," Canadian Census Analyser, Toronto:Ontario. Accessed April 13, 2019.</a> <a href="http://dc1.chass.utoronto.ca/census/index.html">http://dc1.chass.utoronto.ca/census/index.html</a></p>'), outputFileHtmlCon) 
    } 
  }
  
  # Facts table references - footnotes
  # R needs a full path to find the settings file.
  #rmariadb.settingsfile<-"C:\\ProgramData\\MySQL\\MySQL Server 8.0\\oc_transpo_maps.cnf"
  
  #rmariadb.db<-"oc_transpo_maps"
  #footnotesDb<-dbConnect(RMariaDB::MariaDB(),default.file=rmariadb.settingsfile,group=rmariadb.db) 

  output_query_footnotes<-paste0("SELECT oc_transpo_maps.tbl_footnotes.footnote_number,oc_transpo_maps.tbl_footnotes.footnote_text FROM oc_transpo_maps.tbl_facts LEFT JOIN oc_transpo_maps.tbl_footnotes ON oc_transpo_maps.tbl_facts.footnote_number = oc_transpo_maps.tbl_footnotes.footnote_number WHERE oc_transpo_maps.tbl_facts.fact_map_year_start<=",generateYear," AND oc_transpo_maps.tbl_facts.fact_map_year_end>=",generateYear," GROUP BY oc_transpo_maps.tbl_footnotes.footnote_number ORDER BY oc_transpo_maps.tbl_footnotes.footnote_number;")
  
  #A kluge to use 1953, but worth it to avoid complexity
  if(generateYear==1953 | generateYear==1954){
    output_query_footnotes<-paste0("SELECT oc_transpo_maps.tbl_footnotes.footnote_number,oc_transpo_maps.tbl_footnotes.footnote_text FROM oc_transpo_maps.tbl_facts LEFT JOIN oc_transpo_maps.tbl_footnotes ON oc_transpo_maps.tbl_facts.footnote_number = oc_transpo_maps.tbl_footnotes.footnote_number WHERE oc_transpo_maps.tbl_facts.fact_map_year_start<=1954 AND oc_transpo_maps.tbl_facts.fact_map_year_end>=1954 GROUP BY oc_transpo_maps.tbl_footnotes.footnote_number ORDER BY oc_transpo_maps.tbl_footnotes.footnote_number;")
  }
  #Special maps - generate all footnotes
  if(generateYear==9999){
    output_query_footnotes<-paste0("SELECT oc_transpo_maps.tbl_footnotes.footnote_number,oc_transpo_maps.tbl_footnotes.footnote_text FROM oc_transpo_maps.tbl_facts LEFT JOIN oc_transpo_maps.tbl_footnotes ON oc_transpo_maps.tbl_facts.footnote_number = oc_transpo_maps.tbl_footnotes.footnote_number WHERE true GROUP BY oc_transpo_maps.tbl_footnotes.footnote_number ORDER BY oc_transpo_maps.tbl_footnotes.footnote_number;")
  }
  #print(output_query_footnotes)
  
  output_rs_footnotes = dbSendQuery(routesDb,output_query_footnotes)
  output_dbRows_footnotes<-dbFetch(output_rs_footnotes, 999999)
  if (nrow(output_dbRows_footnotes)==0){
    #print (paste0("Zero footnote rows for ",generateYear))
    dbClearResult(output_rs_footnotes)
  } else {
    
    for (i_footnotes in 1:nrow(output_dbRows_footnotes)) {
      writeLines(paste0('<p><a name="footnote',output_dbRows_footnotes[i_footnotes, 1],'">',output_dbRows_footnotes[i_footnotes, 1]," ", output_dbRows_footnotes[i_footnotes, 2],'</a></p>'), outputFileHtmlCon)
    }
    
    dbClearResult(output_rs_footnotes)
  }
  #dbDisconnect(footnotesDb)  
  
}

genHTMLEndBody<-function(outputFileHtmlCon){
  writeLines(paste0("<hr>"), outputFileHtmlCon)
  writeLines(paste0("<p>Page last modifed: ", format(Sys.Date(),"%d %B, %Y"),"</p>"), outputFileHtmlCon)
  writeLines(paste0("</body>"), outputFileHtmlCon)
  writeLines(paste0("</html>"), outputFileHtmlCon)
}

library(RMariaDB)

# R needs a full path to find the settings file.
rmariadb.settingsfile<-"C:\\ProgramData\\MySQL\\MySQL Server 8.0\\oc_transpo_maps.cnf"

rmariadb.db<-"oc_transpo_maps"
routesDb<-dbConnect(RMariaDB::MariaDB(),default.file=rmariadb.settingsfile,group=rmariadb.db) 

# list the table. This confirms we connected to the database.
dbListTables(routesDb)


#Generate links
pageLinks="";
for (generateYear in 1929:2015){
  
  print(paste0("Making links for year ", generateYear))
  
  #There are 2 files for 1954, so do this twice for June and Dec.
  mapYear=generateYear
  output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE YEAR=",mapYear," ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
  #A kluge to use 1953, but worth it to avoid complexity
  if(generateYear==1953){
    mapYear="1954_June"    
    output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_June' ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
  }
  if(generateYear==1954){
    mapYear="1954_December"
    output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_December' ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
  }
  
  output_rs = dbSendQuery(routesDb,output_query)
  output_dbRows<-dbFetch(output_rs, 999999)
  if (nrow(output_dbRows)==0){
    dbClearResult(output_rs)
  } else {
    pageLinks<-paste0(pageLinks,"<a href='",mapYear,".html'>",mapYear,"</a> | ")
    dbClearResult(output_rs)
  }
}
#Add two extra page links
#pageLinks<-paste0(pageLinks,"<a href='urbanextent.html'>Urban Extent 1925-2012</a> | ")
pageLinks<-paste0(pageLinks,"<a href='railonly.html'>Rail routes only 1929-2015</a> | ")
pageLinks<-paste0(pageLinks,"<a href='majorchanges.html'>Major Changes 1929-2015</a> | ")
pageLinks<-paste0(pageLinks,"<a href='timeline.html'>Timeline 1929-2015</a> | ")
pageLinks<-paste0(pageLinks,"<a href='index.html'>Landing page</a>")

#Javascript objects to hold data for use on the animated pages like railonly and major changes.
railOnlyJavaScriptObjects="var railOnly = new Object();\n"
railOnlyArrayCount=0
majorChangesJavaScriptObjects="var majorChanges = new Object();\n"
majorChangesArrayCount=0

for (generateYear in 1929:2015){
  
  #There are 2 files for 1954, so do this twice for June and Dec.
  mapYear=generateYear
  output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE YEAR=",mapYear," ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
  #A kluge to use 1953, but worth it to avoid complexity
  if(generateYear==1953){
    mapYear="1954_June"    
    output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_June' ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
  }
  if(generateYear==1954){
    mapYear="1954_December"
    output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_December' ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
  }

  output_rs = dbSendQuery(routesDb,output_query)
  output_dbRows<-dbFetch(output_rs, 999999)
  if (nrow(output_dbRows)==0){
    print (paste0("Zero rows for ",mapYear))
    dbHasCompleted(output_rs)
    dbClearResult(output_rs)
    
  } else {
    #print(paste0("Generating maps and geojson for year ", mapYear))  
    #which urban growth year to use?
    urbanGrowthYear=1925
    if(generateYear>=1929 & generateYear<1945){
      urbanGrowthYear=1925  
    } else {
      if(generateYear>=1945 & generateYear<1956){
        urbanGrowthYear=1945  
      } else {
        if(generateYear>=1956 & generateYear<1976){
          urbanGrowthYear=1956  
        } else {
          if(generateYear>=1976 & generateYear<1996){
            urbanGrowthYear=1976  
          } else {
            if(generateYear>=1996 & generateYear<2008){
              urbanGrowthYear=1996  
            } else {
              if(generateYear>=2008 & generateYear<2012){
                urbanGrowthYear=2008  
              } else {
                if(generateYear>=2012 & generateYear<2016){
                  urbanGrowthYear=2012  
                } else {
                  #This would be a problem.
                  urbanGrowthYear=1925              
                }
              }
            }
          }
        }
      }  
    }
    
    censusYear=0
    censusCMA_no=10
    if(generateYear>=1961 & generateYear<1971){
      censusYear=1961
      censusCMA_no=6
    } else {
      if(generateYear>=1971 & generateYear<1976){
        censusYear=1971  
        censusCMA_no=10
      } 
    }
    
    dbHasCompleted(output_rs)
    dbClearResult(output_rs)
    outputFileHtml <- paste0("C:\\a_orgs\\carleton\\hist3814\\R\\oc-transpo-maps-data\\output\\",mapYear,".html")
    outputFileHtmlCon<-file(outputFileHtml, open = "w")
    
    genMapHTMLTop(outputFileHtmlCon, mapYear)
    genMapHTMLScriptTop(outputFileHtmlCon, mapYear)  
   
    
    if(censusYear==1961 | censusYear==1971){
      writeLines(paste0("function colorValue(percent) {"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>100) {percent=100;}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent<0) {percent=0;}"), outputFileHtmlCon)
      writeLines(paste0("   hex = ((percent/100*255) >> 0).toString(16);"), outputFileHtmlCon)
      writeLines(paste0("   if(hex.length==1){"), outputFileHtmlCon)
      writeLines(paste0("      hex='0'+hex;"), outputFileHtmlCon)
      writeLines(paste0("   }"), outputFileHtmlCon)
      writeLines(paste0("   return hex;"), outputFileHtmlCon) 
      writeLines(paste0("}"), outputFileHtmlCon)
    
      #Thanks http://colorbrewer2.org/#type=sequential&scheme=RdPu&n=9
      writeLines(paste0("function chloroplethValue(percent) {"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>100) {percent=100;}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent<0) {percent=0;}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=40  & percent<100) {return '#49006a';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=30 & percent<40) {return '#7a0177';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=25 & percent<30) {return '#ae017e';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=20 & percent<25) {return '#dd3497';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=15 & percent<20) {return '#f768a1';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=10 & percent<15) {return '#fa9fb5';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=6 & percent<10) {return '#fcc5c0';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=3 & percent<6) {return '#fde0dd';}"), outputFileHtmlCon)
      writeLines(paste0("   if(percent>=0 & percent<3){return '#fff7f3';}"), outputFileHtmlCon)
      # ['#fff7f3','#fde0dd','#fcc5c0','#fa9fb5','#f768a1','#dd3497','#ae017e','#7a0177','#49006a']
      writeLines(paste0("   return '#fff7f3';"), outputFileHtmlCon) 
      writeLines(paste0("}"), outputFileHtmlCon)
    }
    
    writeLines(paste0(''), outputFileHtmlCon)
    # ['#fff7f3','#fde0dd','#fcc5c0','#fa9fb5','#f768a1','#dd3497','#ae017e','#7a0177','#49006a']
    
    writeLines(paste0('  window.onload = function() {'), outputFileHtmlCon)
    # Some early years have historical maps available. Load these as the basemap instead of OpenStreetMap
    if(generateYear>=1929 & generateYear<1939){
      writeLines(paste0("    var basemap = L.tileLayer('http://www.jeffblackadar.ca/oc-transpo/1927/{z}/{x}/{y}.png', {"), outputFileHtmlCon)
      writeLines(paste0("      attribution: '",'<a href="http://geo1.scholarsportal.info">Scholars Geoportal</a>',' | <a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">MacOdrum Library</a>',"'"), outputFileHtmlCon)
      writeLines(paste0("    });"), outputFileHtmlCon)
      basemapTitle="Topo. Map 1927"
    }else{
      if(generateYear>=1939 & generateYear<1948){
        writeLines(paste0("    var basemap = L.tileLayer('http://www.jeffblackadar.ca/oc-transpo/1939/{z}/{x}/{y}.png', {"), outputFileHtmlCon)
        writeLines(paste0("      attribution: '",'<a href="http://geo1.scholarsportal.info">Scholars Geoportal</a>',' | <a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">MacOdrum Library</a>',"'"), outputFileHtmlCon)
        writeLines(paste0("    });"), outputFileHtmlCon)
        basemapTitle="Topo. Map 1939"
      }else{
        if(generateYear>=1948 & generateYear<1953){
          writeLines(paste0("    var basemap = L.tileLayer('http://www.jeffblackadar.ca/oc-transpo/1948/{z}/{x}/{y}.png', {"), outputFileHtmlCon)
          writeLines(paste0("      attribution: '",'<a href="http://geo1.scholarsportal.info">Scholars Geoportal</a>',' | <a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">MacOdrum Library</a>',"'"), outputFileHtmlCon)
          writeLines(paste0("    });"), outputFileHtmlCon)
          basemapTitle="Topo. Map 1948"
        }else{
          writeLines(paste0("    var basemap = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {"), outputFileHtmlCon)
          writeLines(paste0("      attribution: '&copy; ",'<a href="http://osm.org/copyright">OpenStreetMap</a>',' contributors | <a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">MacOdrum Library</a>',"'"), outputFileHtmlCon)
          writeLines(paste0("    });"), outputFileHtmlCon)
          basemapTitle="Open Street Map Today"
        }
      }
    }
  
    genMapHTMLMapTop(outputFileHtmlCon)
    
    

    #routeTypes is used for the documentation below the map.
    routeTypes=""
    
    if(censusYear==1961 | censusYear==1971){
      writeLines(paste0("// Census"), outputFileHtmlCon)
      writeLines(paste0("   $.ajax({"), outputFileHtmlCon)
      writeLines(paste0("      type: 'POST',"), outputFileHtmlCon)
      writeLines(paste0("      url: '",censusYear,"_census_auto.geojson',"), outputFileHtmlCon)
      writeLines(paste0("      dataType: 'json',"), outputFileHtmlCon)
      writeLines(paste0("      success: function(response) {"), outputFileHtmlCon)
      writeLines(paste0("         censusAutoLayer = L.geoJson(response, {"), outputFileHtmlCon)
      writeLines(paste0("         "), outputFileHtmlCon)
      writeLines(paste0("         onEachFeature: function (feature, layer) {"), outputFileHtmlCon)
      writeLines(paste0("            "), outputFileHtmlCon)
      writeLines(paste0("            if(feature.properties.CMA_no==",censusCMA_no,"){"), outputFileHtmlCon)
      writeLines(paste0("               layer.bindPopup('<h3>Census ",censusYear," '+feature.properties.CMA_name+'</h3><table><tr><td>No Automobile: (*)</td><td>'+feature.properties.auto_none+'</td><td>'+feature.properties.auto_none_100+'%</td></tr><tr><td>One Automobile:</td><td>'+feature.properties.auto_one+'</td><td>'+feature.properties.auto_one_100+'%</td></tr><tr><td>Two Automobiles:</td><td>'+feature.properties.auto_two+'</td><td>'+feature.properties.auto_two_100+'%</td></tr><tr><td>CMA number:</td><td>'+feature.properties.CMA_no+'</td><td></td></tr><td>Census Tract:</td><td>'+feature.properties.CT+'</td><td></td></tr><table>');"), outputFileHtmlCon)
      writeLines(paste0("               layer.setStyle({"), outputFileHtmlCon)
      writeLines(paste0("                  color: 'white',"), outputFileHtmlCon)
      writeLines(paste0("                  fillColor: chloroplethValue(feature.properties.auto_none_100),"), outputFileHtmlCon)
      writeLines(paste0("                  weight: 0,"), outputFileHtmlCon)
      writeLines(paste0("                  opacity: 0,"), outputFileHtmlCon)
      writeLines(paste0("                  fillOpacity: .7"), outputFileHtmlCon)
      writeLines(paste0("                });"), outputFileHtmlCon)
      writeLines(paste0("             }"), outputFileHtmlCon)
      writeLines(paste0("             else{"), outputFileHtmlCon)
      writeLines(paste0("                layer.setStyle({"), outputFileHtmlCon)
      writeLines(paste0("                   color: 'white',"), outputFileHtmlCon)
      writeLines(paste0("                   weight: 0,"), outputFileHtmlCon)
      writeLines(paste0("                   opacity: 0"), outputFileHtmlCon)
      writeLines(paste0("                });"), outputFileHtmlCon)
      writeLines(paste0("             }"), outputFileHtmlCon)
      writeLines(paste0("          }"), outputFileHtmlCon)
      writeLines(paste0("       });"), outputFileHtmlCon)
      writeLines(paste0("          censusAutoLayer.addTo(map);"), outputFileHtmlCon)
      writeLines(paste0("          controlLayers.addOverlay(censusAutoLayer, '% No Automobile owned, ",censusYear," census');"), outputFileHtmlCon)
      writeLines(paste0("        }"), outputFileHtmlCon)
      writeLines(paste0("      });"), outputFileHtmlCon)
      writeLines(paste0(""), outputFileHtmlCon)
    }
    

    
    genHTMLUrbanExtent(outputFileHtmlCon,urbanGrowthYear)    
    
    
    #marker.bindPopup("<b>Hello world!</b><br>I am a popup.").openPopup();
    #var marker = L.marker([51.5, -0.09]).addTo(mymap);
    
    output_query_markers<-paste0("SELECT tbl_facts.fact,tbl_facts.footnote_number,tbl_markers.marker_latitude,tbl_markers.marker_longitude,tbl_markers.id,tbl_markers.marker_route_known FROM oc_transpo_maps.tbl_markers LEFT JOIN tbl_facts ON tbl_markers.fact_id = tbl_facts.id WHERE marker_map_year_start<=",generateYear," AND marker_map_year_end>=",generateYear,";")
    #A kluge to use 1953, but worth it to avoid complexity
    if(generateYear==1953 | generateYear==1954){
      output_query_markers<-paste0("SELECT tbl_facts.fact,tbl_facts.footnote_number,tbl_markers.marker_latitude,tbl_markers.marker_longitude,tbl_markers.id,tbl_markers.marker_route_known FROM oc_transpo_maps.tbl_markers LEFT JOIN tbl_facts ON tbl_markers.fact_id = tbl_facts.id WHERE marker_map_year_start<=1954 AND marker_map_year_end>=1954;")
    }
    
    output_rs_markers = dbSendQuery(routesDb,output_query_markers)
    output_dbRows_markers<-dbFetch(output_rs_markers, 999999)
    if (nrow(output_dbRows_markers)==0){
      print (paste0("Zero rows for ",generateYear))
      dbHasCompleted(output_rs_markers)
      dbClearResult(output_rs_markers)
    } else {
      for (i_facts in 1:nrow(output_dbRows_markers)) {
        writeLines(paste0("var marker",output_dbRows_markers[i_facts, 5],"= L.marker([",output_dbRows_markers[i_facts, 3],", ",output_dbRows_markers[i_facts, 4],"]).addTo(map);"), outputFileHtmlCon)
        if(output_dbRows_markers[i_facts, 6]==0) {
          writeLines(paste0("marker",output_dbRows_markers[i_facts, 5],".bindPopup('<p>",output_dbRows_markers[i_facts, 1],' <a href="#footnote',output_dbRows_markers[i_facts, 2],'"><sup>',output_dbRows_markers[i_facts, 2],"</sup></a></p><p>The route map for this bus line is not known for this year.</p>').openPopup();"), outputFileHtmlCon)
        }else{
          writeLines(paste0("marker",output_dbRows_markers[i_facts, 5],".bindPopup('<p>",output_dbRows_markers[i_facts, 1],' <a href="#footnote',output_dbRows_markers[i_facts, 2],'"><sup>',output_dbRows_markers[i_facts, 2],"</sup></a></p>').openPopup();"), outputFileHtmlCon)
        }
      }
      dbHasCompleted(output_rs_markers)
      dbClearResult(output_rs_markers)
    }

    #Write a layer for each route type
    output_query_route_style<-paste0("SELECT tbl_route_maps.RTE_TYPE, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE, tbl_route_types.RTE_TYPE_MODE_CODE2, tbl_route_types.RTE_TYPE_MAP_COLOR FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE YEAR=",mapYear," GROUP BY RTE_TYPE ORDER BY RTE_TYPE DESC;")
    #A kluge to use 1953, but worth it to avoid complexity
    if(generateYear==1953){
      mapYear="1954_June"    
      #output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_June' ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
      output_query_route_style<-paste0("SELECT tbl_route_maps.RTE_TYPE, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE, tbl_route_types.RTE_TYPE_MODE_CODE2, tbl_route_types.RTE_TYPE_MAP_COLOR FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_June' GROUP BY RTE_TYPE ORDER BY RTE_TYPE DESC;")
    }
    if(generateYear==1954){
      mapYear="1954_December"
      #output_query<-paste0("SELECT tbl_route_maps.ID, tbl_route_maps.RTE_SHP_FILE_NAME, tbl_route_maps.RTE_SHP_FILE_FOLDER, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_maps.RTE_NUM, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_December' ORDER BY RTE_TYPE_MODE_CODE DESC, RTE_NUM;")
      output_query_route_style<-paste0("SELECT tbl_route_maps.RTE_TYPE, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE, tbl_route_types.RTE_TYPE_MODE_CODE2, tbl_route_types.RTE_TYPE_MAP_COLOR FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_December' GROUP BY RTE_TYPE ORDER BY RTE_TYPE DESC;")
    }
    output_rs_route_style = dbSendQuery(routesDb,output_query_route_style)
    output_dbRows_route_style<-dbFetch(output_rs_route_style, 999999)
    if (nrow(output_dbRows_route_style)==0){
      #print (paste0("Zero rows for ",mapYear))
      dbHasCompleted(output_rs_route_style)
      dbClearResult(output_rs_route_style)
    } else {
      for (i_route_style in 1:nrow(output_dbRows_route_style)) {
        print(paste0("To map ", mapYear, ", adding: ",output_dbRows_route_style[i_route_style, 1]))

        routeLayerName <- paste0("layer",gsub("-","",gsub(" ","",output_dbRows_route_style[i_route_style, 1])))
        
        writeLines(paste0(""), outputFileHtmlCon)
        writeLines(paste0("// layer for ",output_dbRows_route_style[i_route_style, 1]), outputFileHtmlCon)
        writeLines(paste0("var ",routeLayerName,";"), outputFileHtmlCon)
        
        writeLines(paste0("      $.ajax({"), outputFileHtmlCon)
        writeLines(paste0("        type: 'POST',"), outputFileHtmlCon)
        writeLines(paste0("        url: '",mapYear,"-",gsub(" ","-",output_dbRows_route_style[i_route_style, 1]),".geojson',"), outputFileHtmlCon)
        writeLines(paste0("        dataType: 'json',"), outputFileHtmlCon)
        writeLines(paste0("        success: function(response) {"), outputFileHtmlCon)
        writeLines(paste0("          ",routeLayerName," = L.geoJson(response, {"), outputFileHtmlCon)
        # Only need attribution once.
        #if(i_route_style ==1){
        #writeLines(paste0("      attribution: '",'<a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">Carleton University</a>'," ';"), outputFileHtmlCon)
        #}
        writeLines("             onEachFeature: function (feature, layer) {", outputFileHtmlCon)
        if(generateYear<=1948){
          writeLines(paste0("                 layer.bindPopup('<h3>Route Name: '+feature.properties.RTE_NAME+'</h3><p>'+feature.properties.RTE_TYPE+'</p><p>'+feature.properties.MODE+'</p>');"), outputFileHtmlCon)  
        }else{
          writeLines(paste0("                 layer.bindPopup('<h3>Route Number: '+feature.properties.RTE_NUM+'</h3><p>'+feature.properties.RTE_TYPE+'</p><p>'+feature.properties.MODE+'</p>');"), outputFileHtmlCon)  
        }
        
        writeLines(paste0("               }"), outputFileHtmlCon)
        writeLines(paste0("             });"), outputFileHtmlCon)
        writeLines(paste0("          ",routeLayerName,".setStyle({"), outputFileHtmlCon)
        writeLines(paste0("            color: '",output_dbRows_route_style[i_route_style, 6],"',"), outputFileHtmlCon)
        routeTypes <- paste0(routeTypes,"<span style=",'"color:',output_dbRows_route_style[i_route_style, 6],'"',">",output_dbRows_route_style[i_route_style, 1]," ___________</span><br>")
        writeLines(paste0("            weight: 3,"), outputFileHtmlCon)
        writeLines(paste0('            opacity: 1'), outputFileHtmlCon)
        writeLines(paste0("          });"), outputFileHtmlCon)
        writeLines(paste0("          ",routeLayerName,".addTo(map);"), outputFileHtmlCon)
        writeLines(paste0("          controlLayers.addOverlay(",routeLayerName,", '<span style=",'"color:',output_dbRows_route_style[i_route_style, 6],'"',">",output_dbRows_route_style[i_route_style, 1],"</span>');"), outputFileHtmlCon)
        writeLines(paste0("        }"), outputFileHtmlCon)
        writeLines(paste0("      });"), outputFileHtmlCon)
        writeLines(paste0(""), outputFileHtmlCon)
      }
      dbHasCompleted(output_rs_route_style)
      dbClearResult(output_rs_route_style)
    }

    writeLines(paste0("      controlLayers.addOverlay(basemap, '",basemapTitle,"');"), outputFileHtmlCon)
    writeLines(paste0("      "), outputFileHtmlCon)
    writeLines(paste0("//    });"), outputFileHtmlCon)
    writeLines(paste0("  };"), outputFileHtmlCon)
    writeLines(paste0("</script>"), outputFileHtmlCon)
    
    
    if(censusYear==1961 | censusYear==1971){
      if(censusYear==1961){
        writeLines(paste0('<p>Census Data: % population owning no automobile.<a href="#rcensus1961"><sup>6</sup></a></p>'), outputFileHtmlCon)
      }
      if(censusYear==1971){
        writeLines(paste0('<p>Census Data: % population owning no automobile.<a href="#rcensus1971"><sup>7</sup></a></p>'), outputFileHtmlCon)
      }
      writeLines(paste0("<table><tr>"), outputFileHtmlCon)
      writeLines(paste0("<script>"), outputFileHtmlCon)
      writeLines(paste0("for(counter=0;counter<=100;counter=counter+2){"), outputFileHtmlCon)
      
      writeLines(paste0("document.write('<td bgcolor='+chloroplethValue(counter)+'>&nbsp;&nbsp;</td>');"), outputFileHtmlCon)
      writeLines(paste0(""), outputFileHtmlCon)
      writeLines(paste0("}"), outputFileHtmlCon)
      writeLines(paste0(""), outputFileHtmlCon)
      writeLines(paste0(""), outputFileHtmlCon)
      writeLines(paste0(""), outputFileHtmlCon)
      writeLines(paste0(""), outputFileHtmlCon)
      writeLines(paste0("</script>"), outputFileHtmlCon)
      writeLines(paste0("</tr>"), outputFileHtmlCon)
      writeLines(paste0("<tr>"), outputFileHtmlCon)
      for(tdCounter in 1:10){
        writeLines(paste0("<td colspan=5>",tdCounter*10,"%</td>"), outputFileHtmlCon)
      }
      writeLines(paste0("</tr>"), outputFileHtmlCon)
      writeLines(paste0("</table>"), outputFileHtmlCon)
    }
    writeLines(paste0('<h1>',genPageTitle(mapYear),'</h1>'), outputFileHtmlCon)
    writeLines(paste0('<p><a href="references.pdf">References used for this project.</a></p>'), outputFileHtmlCon)
    
    writeLines(paste0("<h2>Legend</h2>"), outputFileHtmlCon)
    writeLines(paste0("<h3>Route types</h3>"), outputFileHtmlCon)
    writeLines(paste0('<p>',routeTypes,'<a href="#roctranspogis"><sup>1</sup></a></p>'), outputFileHtmlCon)
    writeLines(paste0("<p>Each route can be clicked to view its route number and mode. Due to overlapping routes and layers, the route may be below other information on the map and not clickable. To bring it to the top of the map layers, click the layer twice in the control box at the top right portion of the map.</p>"), outputFileHtmlCon)
    writeLines(paste0("<h3>Urban Extent</h3>"), outputFileHtmlCon)
    writeLines(paste0('<p>This layer shows the urban extent of the Ottawa-Gatineau region for the year ',urbanGrowthYear,'. It is based on data compiled by the NCC and available at Carleton University&apos;s MacOdrum Library.<a href="#rnccue"><sup>2</sup></p></a>'), outputFileHtmlCon)
    
    writeLines(paste0("<h3>Base map</h3>"), outputFileHtmlCon)
    writeLines(paste0("<p>",basemapTitle," is the base map used to provide context for the mass transit routes."), outputFileHtmlCon)
    
    #National Defence Map references
    if(generateYear>=1929 & generateYear<1939){
      writeLines(paste0('<a href="#rmap1927"><sup>3</sup></a></p>'), outputFileHtmlCon)
    }else{
      if(generateYear>=1939 & generateYear<1948){
        writeLines(paste0('<a href="#rmap1939"><sup>4</sup></a></p>'), outputFileHtmlCon)
      }else{
        if(generateYear>=1948 & generateYear<1953){
          writeLines(paste0('<a href="#rmap1948"><sup>5</sup></a></p>'), outputFileHtmlCon)
        }else{
          writeLines(paste0('<a href="#rmaposm"><sup>8</sup></a></p>'), outputFileHtmlCon)
        }
      }
    }
    
    

    
    genHTMLPageLinks(outputFileHtmlCon,pageLinks)
    
    writeLines(paste0("<h2>List of routes</h2>"), outputFileHtmlCon)
    writeLines(paste0("<table>"), outputFileHtmlCon)
    
    if(generateYear<=1948){
      writeLines(paste0("<tr><th>Map<br>line<br>colour</th><th>Route<br>name</th><th>Route type</th><th>Route mode</th></tr>"), outputFileHtmlCon)
    }else{
      writeLines(paste0("<tr><th>Map<br>line<br>colour</th><th>Route<br>number</th><th>Route type</th><th>Route mode</th></tr>"), outputFileHtmlCon)
    }
    output_query_route_style<-paste0("SELECT tbl_route_maps.RTE_TYPE, tbl_route_maps.RTE_NUM, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE, tbl_route_types.RTE_TYPE_MODE_CODE2, tbl_route_types.RTE_TYPE_MAP_COLOR FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE YEAR=",mapYear," ORDER BY RTE_NUM,RTE_TYPE;")
    #A kluge to use 1953, but worth it to avoid complexity
    if(generateYear==1953){
      mapYear="1954_June"    
      output_query_route_style<-paste0("SELECT tbl_route_maps.RTE_TYPE, tbl_route_maps.RTE_NUM, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE, tbl_route_types.RTE_TYPE_MODE_CODE2, tbl_route_types.RTE_TYPE_MAP_COLOR FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_June' ORDER BY RTE_NUM,RTE_TYPE;")
    }
    if(generateYear==1954){
      mapYear="1954_December"
      output_query_route_style<-paste0("SELECT tbl_route_maps.RTE_TYPE, tbl_route_maps.RTE_NUM, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE, tbl_route_types.RTE_TYPE_MODE_CODE2, tbl_route_types.RTE_TYPE_MAP_COLOR FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE RTE_SHP_FILE_FOLDER='1954_December' ORDER BY RTE_NUM,RTE_TYPE;")
    }
    if(generateYear<=1948){
      output_query_route_style<-paste0("SELECT tbl_route_maps.RTE_TYPE, tbl_route_maps.RTE_NAME, tbl_route_maps.RTE_TYPE_GROOMED, tbl_route_types.RTE_TYPE_MODE, tbl_route_types.RTE_TYPE_MODE_CODE, tbl_route_types.RTE_TYPE_MODE_CODE2, tbl_route_types.RTE_TYPE_MAP_COLOR FROM tbl_route_maps LEFT JOIN tbl_route_types ON tbl_route_maps.RTE_TYPE_GROOMED = tbl_route_types.RTE_TYPE WHERE YEAR=",mapYear," ORDER BY RTE_NUM,RTE_TYPE;")
    }
    #print(output_query_route_style)
    output_rs_route_style = dbSendQuery(routesDb,output_query_route_style)
    output_dbRows_route_style<-dbFetch(output_rs_route_style, 999999)
    if (nrow(output_dbRows_route_style)==0){
      #print (paste0("Zero rows for ",mapYear))
      dbHasCompleted(output_rs_route_style)
      dbClearResult(output_rs_route_style)
    } else {
      for (i_route_style in 1:nrow(output_dbRows_route_style)) {
        #print(paste0("To map ", mapYear, " adding "))
        #print(output_dbRows_route_style[i_route_style, 1])
        routeLayerName <- paste0(gsub("-","",gsub(" ","",output_dbRows_route_style[i_route_style, 1])),"Layer")
        writeLines(paste0("<tr>"), outputFileHtmlCon)
        writeLines(paste0("<td bgcolor='",output_dbRows_route_style[i_route_style, 7],"'>&nbsp;&nbsp;&nbsp;</td>","<td>",output_dbRows_route_style[i_route_style, 2],"</td>","<td>",output_dbRows_route_style[i_route_style, 1],"</td>","<td>",output_dbRows_route_style[i_route_style, 4],"</td>"), outputFileHtmlCon)
        writeLines(paste0("</tr>"), outputFileHtmlCon)
      }
      dbHasCompleted(output_rs_route_style)
      dbClearResult(output_rs_route_style)
    }
    
    writeLines(paste0("</table>"), outputFileHtmlCon)
    
    
    


    output_query_facts<-paste0("SELECT fact,footnote_number,fact_year FROM oc_transpo_maps.tbl_facts WHERE fact_map_year_start<=",generateYear," AND fact_map_year_end>=",generateYear," ORDER BY fact_year;")
    #A kluge to use 1953, but worth it to avoid complexity
    if(generateYear==1953 | generateYear==1954){
      output_query_facts<-paste0("SELECT fact,footnote_number,fact_year FROM oc_transpo_maps.tbl_facts WHERE fact_map_year_start<=1954 AND fact_map_year_end>=1954 ORDER BY fact_year;")
    }
    
    output_rs_facts = dbSendQuery(routesDb,output_query_facts)
    output_dbRows_facts<-dbFetch(output_rs_facts, 999999)
    if (nrow(output_dbRows_facts)==0){
      print (paste0("Zero rows for ",generateYear))
      dbHasCompleted(output_rs_facts)
      dbClearResult(output_rs_facts)
    } else {
      writeLines(paste0("<h2>Facts and Observations.</h2>"), outputFileHtmlCon)
      writeLines(paste0("<ul>"), outputFileHtmlCon)
      for (i_facts in 1:nrow(output_dbRows_facts)) {
        writeLines(paste0("<li>",output_dbRows_facts[i_facts, 3],": ",output_dbRows_facts[i_facts, 1],'<a href="#footnote',output_dbRows_facts[i_facts, 2],'"><sup>',output_dbRows_facts[i_facts, 2],'</sup></a></p>'), outputFileHtmlCon)
      }
      writeLines(paste0("</ul>"), outputFileHtmlCon)
      dbHasCompleted(output_rs_facts)
      dbClearResult(output_rs_facts)
    }
    
    
    writeLines(paste0("<hr>"), outputFileHtmlCon)
    genHTMLFootnotes(outputFileHtmlCon,generateYear)
    
    genHTMLEndBody(outputFileHtmlCon)

    close(outputFileHtmlCon)

    #--------------------------------------------
    # Animated maps - Javascript objects
    #--------------------------------------------
    
    # update this value to hold objects used for the animated rail only map.
    if(generateYear==1929|generateYear==1951|generateYear==1962|generateYear==1983|generateYear==1986|generateYear==1996){
      majorChangesJavaScriptObjects<-paste0(majorChangesJavaScriptObjects, 'majorChanges[',majorChangesArrayCount,']=({mapYear:',generateYear,',geojsonMajorChangesYear:',generateYear,',geojsonUrbanGrowthYear:',urbanGrowthYear,'});','\n')
      majorChangesArrayCount=majorChangesArrayCount+1
    }
    
    if(generateYear<=1959 & generateYear!=1953){
      railOnlyJavaScriptObjects<-paste0(railOnlyJavaScriptObjects, 'railOnly[',railOnlyArrayCount,']=({mapYear:',generateYear,',geojsonRailYear:',generateYear,',geojsonUrbanGrowthYear:',urbanGrowthYear,'});','\n')
      railOnlyArrayCount<-railOnlyArrayCount+1
    }else{
      if(generateYear>1959 & generateYear<2001){
        railOnlyJavaScriptObjects<-paste0(railOnlyJavaScriptObjects, 'railOnly[',railOnlyArrayCount,']=({mapYear:',generateYear,',geojsonRailYear:0',',geojsonUrbanGrowthYear:',urbanGrowthYear,'});','\n')
        railOnlyArrayCount<-railOnlyArrayCount+1
      }else{
        if(generateYear>=2000){
          railOnlyJavaScriptObjects<-paste0(railOnlyJavaScriptObjects, 'railOnly[',railOnlyArrayCount,']=({mapYear:',generateYear,',geojsonRailYear:',generateYear,',geojsonUrbanGrowthYear:',urbanGrowthYear,'});','\n')
          railOnlyArrayCount<-railOnlyArrayCount+1
        }else{
          print("This is a problem.")
        }
      }
    }
  }
}

#Make a javaScript object to hold facts 
factsJavaScriptObjects="var facts = {\n"


output_query_facts<-paste0("SELECT fact,footnote_number,fact_year,fact_map_year_start,fact_map_year_end FROM oc_transpo_maps.tbl_facts WHERE true ORDER BY fact_map_year_start, fact_year;")
output_rs_facts = dbSendQuery(routesDb,output_query_facts)
output_dbRows_facts<-dbFetch(output_rs_facts, 999999)
if (nrow(output_dbRows_facts)==0){
  print (paste0("Zero rows for timeline"))
  dbHasCompleted(output_rs_facts)
  dbClearResult(output_rs_facts)
} else {
  timeLineYear=0
  timeLineMapYear=0
  for (i_facts in 1:nrow(output_dbRows_facts)) {
    if(timeLineMapYear!=output_dbRows_facts[i_facts, 4]){
      if(timeLineMapYear!=0){
        factsJavaScriptObjects<-paste0(factsJavaScriptObjects,"',\n")
      }
      factsJavaScriptObjects<-paste0(factsJavaScriptObjects,output_dbRows_facts[i_facts, 4], ":'")
    }
    timeLineMapYear=output_dbRows_facts[i_facts, 4]
    if(timeLineYear!=output_dbRows_facts[i_facts, 3]){
      factsJavaScriptObjects<-paste0(factsJavaScriptObjects,"<b>",output_dbRows_facts[i_facts, 3],":</b></p>")
    }
    timeLineYear=output_dbRows_facts[i_facts, 3]
    factsJavaScriptObjects<-paste0(factsJavaScriptObjects,"<p>",output_dbRows_facts[i_facts, 1],' <a href="#footnote',output_dbRows_facts[i_facts, 2],'"><sup>',output_dbRows_facts[i_facts, 2],'</sup></a></p>')
  }
  dbHasCompleted(output_rs_facts)
  dbClearResult(output_rs_facts)
}

factsJavaScriptObjects<-paste0(factsJavaScriptObjects,"'}\n")


#--------------------------------------------
# Urban Extent Only
#--------------------------------------------

outputFileHtml <- paste0("C:\\a_orgs\\carleton\\hist3814\\R\\oc-transpo-maps-data\\output\\urbanextent.html")
outputFileHtmlCon<-file(outputFileHtml, open = "w")

genMapHTMLTop(outputFileHtmlCon, "Urban extent 1929-2015")
genMapHTMLScriptTop(outputFileHtmlCon, "Urban extent 1929-2015")

writeLines(paste0('  window.onload = function() {'), outputFileHtmlCon)
writeLines(paste0("    var basemap = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {"), outputFileHtmlCon)
writeLines(paste0("      attribution: '&copy; ",'<a href="http://osm.org/copyright">OpenStreetMap</a>',' contributors | <a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">MacOdrum Library</a>',"'"), outputFileHtmlCon)
writeLines(paste0("    });"), outputFileHtmlCon)
basemapTitle="Open Street Map Today"

genMapHTMLMapTop(outputFileHtmlCon)

genHTMLUrbanExtent(outputFileHtmlCon,1925)
genHTMLUrbanExtent(outputFileHtmlCon,1945)
genHTMLUrbanExtent(outputFileHtmlCon,1956)
genHTMLUrbanExtent(outputFileHtmlCon,1976)
genHTMLUrbanExtent(outputFileHtmlCon,1996)
genHTMLUrbanExtent(outputFileHtmlCon,2008)
genHTMLUrbanExtent(outputFileHtmlCon,2012)
writeLines(paste0("      controlLayers.addOverlay(basemap, '",basemapTitle,"');"), outputFileHtmlCon)
writeLines(paste0("      "), outputFileHtmlCon)
writeLines(paste0("  };"), outputFileHtmlCon)

writeLines(paste0("var controlChoices=document.getElementsByClassName('leaflet-control-layers-selector');"), outputFileHtmlCon)
writeLines(paste0("var animLayer=0;"), outputFileHtmlCon)

writeLines(paste0("// The years of urban growth data and their order."), outputFileHtmlCon)
writeLines(paste0("var urbanExtentYears = ["), outputFileHtmlCon)
writeLines(paste0("[1925, 1],"), outputFileHtmlCon)
writeLines(paste0("[1945, 2],"), outputFileHtmlCon)
writeLines(paste0("[1956, 3],"), outputFileHtmlCon)
writeLines(paste0("[1976, 4],"), outputFileHtmlCon)
writeLines(paste0("[1996, 5],"), outputFileHtmlCon)
writeLines(paste0("[2008, 6],"), outputFileHtmlCon)
writeLines(paste0("[2012, 7]"), outputFileHtmlCon)
writeLines(paste0("];"), outputFileHtmlCon)
writeLines(paste0("// The years of urban growth data may be out of order on the Leaflet control. "), outputFileHtmlCon)
writeLines(paste0("// Loop through the control, see where each year is and set the year's order in the list."), outputFileHtmlCon)
writeLines(paste0("function checkOrder(){"), outputFileHtmlCon)
writeLines(paste0("   controlChoices=document.getElementsByClassName('leaflet-control-layers-selector');"), outputFileHtmlCon)
writeLines(paste0("   for(cc2 = 0;cc2<urbanExtentYears.length;cc2=cc2+1){"), outputFileHtmlCon)
writeLines(paste0("      ue='Urban Extent '+urbanExtentYears[cc2][0];"), outputFileHtmlCon)
writeLines(paste0("      ue=ue.trim();"), outputFileHtmlCon)
writeLines(paste0("      for(cc = 1;cc<controlChoices.length;cc=cc+1){"), outputFileHtmlCon)
writeLines(paste0("         cchoice=controlChoices[cc].labels[0].innerText;"), outputFileHtmlCon)
writeLines(paste0("         cchoice=cchoice.trim();"), outputFileHtmlCon)
writeLines(paste0('         if(ue===cchoice){'), outputFileHtmlCon)
writeLines(paste0("            urbanExtentYears[cc2][1]=cc;"), outputFileHtmlCon)
writeLines(paste0("            cc=controlChoices.length;"), outputFileHtmlCon)
writeLines(paste0("         }"), outputFileHtmlCon)
writeLines(paste0("      }"), outputFileHtmlCon)
writeLines(paste0("   }"), outputFileHtmlCon)
writeLines(paste0("}"), outputFileHtmlCon)

genHTMLLeafletClickChoiceFunctions(outputFileHtmlCon,pageLinks)
  

writeLines(paste0("function stepAnimate(forward){"), outputFileHtmlCon)
writeLines(paste0("   controlChoices=document.getElementsByClassName('leaflet-control-layers-selector');"), outputFileHtmlCon)
writeLines(paste0("   unClickAll();"), outputFileHtmlCon)
writeLines(paste0("   checkOrder();"), outputFileHtmlCon)
writeLines(paste0("   animLayer=animLayer+forward;"), outputFileHtmlCon)	
writeLines(paste0("   if(animLayer>7){animLayer=1;}"), outputFileHtmlCon)
writeLines(paste0("   if(animLayer<1){animLayer=7;}"), outputFileHtmlCon)
writeLines(paste0("   clickChoice(controlChoices[urbanExtentYears[animLayer-1][1]]);"), outputFileHtmlCon)
writeLines(paste0("}"), outputFileHtmlCon)
writeLines(paste0("</script>"), outputFileHtmlCon)
writeLines(paste0("</table>"), outputFileHtmlCon)
writeLines(paste0('<input type="button" onClick="stepAnimate(1);" value="Animation - Forward in time.">'), outputFileHtmlCon)
writeLines(paste0('<input type="button" onClick="stepAnimate(-1);" value="Animation - Backward in time.">'), outputFileHtmlCon)
writeLines(paste0('<input type="button" onClick="unClickAll();" value="un-check all">'), outputFileHtmlCon)
writeLines(paste0('<input type="button" onClick="clickAll();" value="check all">'), outputFileHtmlCon)

genHTMLPageLinks(outputFileHtmlCon,pageLinks)

writeLines(paste0("<hr>"), outputFileHtmlCon)
genHTMLFootnotes(outputFileHtmlCon,9999)

genHTMLEndBody(outputFileHtmlCon)

close(outputFileHtmlCon)



#--------------------------------------------
# Rail only
#--------------------------------------------

outputFileHtml <- paste0("C:\\a_orgs\\carleton\\hist3814\\R\\oc-transpo-maps-data\\output\\railonly.html")
outputFileHtmlCon<-file(outputFileHtml, open = "w")

genMapHTMLTop(outputFileHtmlCon, "Rail only 1929-2015")
genMapHTMLScriptTop(outputFileHtmlCon, "Rail only 1929-2015")

writeLines(paste0('  window.onload = function() {'), outputFileHtmlCon)
writeLines(paste0("    var basemap = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {"), outputFileHtmlCon)
writeLines(paste0("      attribution: '&copy; ",'<a href="http://osm.org/copyright">OpenStreetMap</a>',' contributors | <a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">MacOdrum Library</a>',"'"), outputFileHtmlCon)
writeLines(paste0("    });"), outputFileHtmlCon)
basemapTitle="Open Street Map Today"

genMapHTMLMapTop(outputFileHtmlCon)

genHTMLUrbanExtent(outputFileHtmlCon,1925)
genHTMLUrbanExtent(outputFileHtmlCon,1945)
genHTMLUrbanExtent(outputFileHtmlCon,1956)
genHTMLUrbanExtent(outputFileHtmlCon,1976)
genHTMLUrbanExtent(outputFileHtmlCon,1996)
genHTMLUrbanExtent(outputFileHtmlCon,2008)
genHTMLUrbanExtent(outputFileHtmlCon,2012)
genHTMLRailOnly(outputFileHtmlCon,1929)
genHTMLRailOnly(outputFileHtmlCon,1939)
genHTMLRailOnly(outputFileHtmlCon,1948)
genHTMLRailOnly(outputFileHtmlCon,1951)
genHTMLRailOnly(outputFileHtmlCon,1954)
genHTMLRailOnly(outputFileHtmlCon,2001)
genHTMLRailOnly(outputFileHtmlCon,2002)
genHTMLRailOnly(outputFileHtmlCon,2003)
genHTMLRailOnly(outputFileHtmlCon,2004)
genHTMLRailOnly(outputFileHtmlCon,2005)
genHTMLRailOnly(outputFileHtmlCon,2006)
genHTMLRailOnly(outputFileHtmlCon,2007)
genHTMLRailOnly(outputFileHtmlCon,2009)
genHTMLRailOnly(outputFileHtmlCon,2010)
genHTMLRailOnly(outputFileHtmlCon,2011)
genHTMLRailOnly(outputFileHtmlCon,2012)
genHTMLRailOnly(outputFileHtmlCon,2013)
genHTMLRailOnly(outputFileHtmlCon,2014)
genHTMLRailOnly(outputFileHtmlCon,2015)

writeLines(paste0("      controlLayers.addOverlay(basemap, '",basemapTitle,"');"), outputFileHtmlCon)
writeLines(paste0("      "), outputFileHtmlCon)
writeLines(paste0("  };"), outputFileHtmlCon)
writeLines(paste0(railOnlyJavaScriptObjects), outputFileHtmlCon)
writeLines(paste0(factsJavaScriptObjects), outputFileHtmlCon)
writeLines(paste0("var controlChoices=document.getElementsByClassName('leaflet-control-layers-selector');"), outputFileHtmlCon)
writeLines(paste0("var animLayer=0;"), outputFileHtmlCon)
writeLines(paste0("var animRailYear=-1;"), outputFileHtmlCon)

writeLines(paste0("// The years of urban growth data and their order."), outputFileHtmlCon)
writeLines(paste0("var urbanExtentYears = ["), outputFileHtmlCon)
writeLines(paste0("[1925, 1],"), outputFileHtmlCon)
writeLines(paste0("[1945, 2],"), outputFileHtmlCon)
writeLines(paste0("[1956, 3],"), outputFileHtmlCon)
writeLines(paste0("[1976, 4],"), outputFileHtmlCon)
writeLines(paste0("[1996, 5],"), outputFileHtmlCon)
writeLines(paste0("[2008, 6],"), outputFileHtmlCon)
writeLines(paste0("[2012, 7]"), outputFileHtmlCon)
writeLines(paste0("];"), outputFileHtmlCon)
writeLines(paste0("// The years of urban growth data may be out of order on the Leaflet control. "), outputFileHtmlCon)
writeLines(paste0("// Loop through the control, see where each year is and set the year's order in the list."), outputFileHtmlCon)
writeLines(paste0("function checkOrder(){"), outputFileHtmlCon)
writeLines(paste0("   controlChoices=document.getElementsByClassName('leaflet-control-layers-selector');"), outputFileHtmlCon)
writeLines(paste0("   for(cc2 = 0;cc2<urbanExtentYears.length;cc2=cc2+1){"), outputFileHtmlCon)
writeLines(paste0("      ue='Urban Extent '+urbanExtentYears[cc2][0];"), outputFileHtmlCon)
writeLines(paste0("      ue=ue.trim();"), outputFileHtmlCon)
writeLines(paste0("      for(cc = 1;cc<controlChoices.length;cc=cc+1){"), outputFileHtmlCon)
writeLines(paste0("         cchoice=controlChoices[cc].labels[0].innerText;"), outputFileHtmlCon)
writeLines(paste0("         cchoice=cchoice.trim();"), outputFileHtmlCon)
writeLines(paste0('         if(ue===cchoice){'), outputFileHtmlCon)
writeLines(paste0("            urbanExtentYears[cc2][1]=cc;"), outputFileHtmlCon)
writeLines(paste0("            cc=controlChoices.length;"), outputFileHtmlCon)
writeLines(paste0("         }"), outputFileHtmlCon)
writeLines(paste0("      }"), outputFileHtmlCon)
writeLines(paste0("   }"), outputFileHtmlCon)
writeLines(paste0("}"), outputFileHtmlCon)

genHTMLLeafletClickChoiceFunctions(outputFileHtmlCon,pageLinks)


writeLines(paste0("function stepAnimate(forward){"), outputFileHtmlCon)
writeLines(paste0("   controlChoices=document.getElementsByClassName('leaflet-control-layers-selector');"), outputFileHtmlCon)
writeLines(paste0("   unClickAll();"), outputFileHtmlCon)
writeLines(paste0("   checkOrder();"), outputFileHtmlCon)
writeLines(paste0("   animLayer=animLayer+forward;"), outputFileHtmlCon)	
writeLines(paste0("   if(animLayer>7){animLayer=1;}"), outputFileHtmlCon)
writeLines(paste0("   if(animLayer<1){animLayer=7;}"), outputFileHtmlCon)
writeLines(paste0("   clickChoice(controlChoices[urbanExtentYears[animLayer-1][1]]);"), outputFileHtmlCon)
writeLines(paste0('   document.getElementById("urbanExtentMapYear").innerHTML = urbanExtentYears[animLayer-1][0];'), outputFileHtmlCon)
writeLines(paste0("}"), outputFileHtmlCon)


writeLines(paste0("function stepAnimateRail(forward){"), outputFileHtmlCon)
writeLines(paste0("  controlChoices=document.getElementsByClassName('leaflet-control-layers-selector');"), outputFileHtmlCon)
writeLines(paste0("  unClickAll();"), outputFileHtmlCon)
writeLines(paste0("  animRailYear=animRailYear+forward;"), outputFileHtmlCon)
writeLines(paste0("  if(animRailYear>44){animRailYear=0;}"), outputFileHtmlCon)
writeLines(paste0("  if(animRailYear<0){animRailYear=44;}"), outputFileHtmlCon)
writeLines(paste0("  document.getElementById('mapYear').innerHTML = railOnly[animRailYear].mapYear;"), outputFileHtmlCon)
writeLines(paste0('  if(typeof facts[railOnly[animRailYear].mapYear] == "undefined"){'), outputFileHtmlCon)
writeLines(paste0("     document.getElementById('mapNotes').innerHTML = '';"), outputFileHtmlCon)
writeLines(paste0('   }else{'), outputFileHtmlCon)
writeLines(paste0("      document.getElementById('mapNotes').innerHTML = '<h3>Map Notes</h3>'+facts[railOnly[animRailYear].mapYear];+'<hr>'"), outputFileHtmlCon)
writeLines(paste0('   }'), outputFileHtmlCon)  
writeLines(paste0("  document.getElementById('urbanExtentMapYear').innerHTML = railOnly[animRailYear].geojsonUrbanGrowthYear;"), outputFileHtmlCon)
writeLines(paste0("  if(railOnly[animRailYear].mapYear>=1929){"), outputFileHtmlCon)
writeLines(paste0("    ue='Urban Extent '+railOnly[animRailYear].geojsonUrbanGrowthYear;"), outputFileHtmlCon)
writeLines(paste0("    ue=ue.trim();"), outputFileHtmlCon)
writeLines(paste0("    ro='';"), outputFileHtmlCon)
writeLines(paste0("    if(railOnly[animRailYear].geojsonRailYear<=1959 & railOnly[animRailYear].geojsonRailYear>0){"), outputFileHtmlCon)
writeLines(paste0("      ro=railOnly[animRailYear].geojsonRailYear+' Street Cars only';"), outputFileHtmlCon)
writeLines(paste0("    }"), outputFileHtmlCon)
writeLines(paste0("    else{"), outputFileHtmlCon)
writeLines(paste0("      if(railOnly[animRailYear].geojsonRailYear>2000){"), outputFileHtmlCon)
writeLines(paste0("        ro=railOnly[animRailYear].geojsonRailYear+' Train only';"), outputFileHtmlCon)
writeLines(paste0("      }"), outputFileHtmlCon)
writeLines(paste0("    }"), outputFileHtmlCon)
writeLines(paste0("    ro=ro.trim();"), outputFileHtmlCon)
writeLines(paste0("    // loop through the choices in the Leaflet control, they may be out of order, depending on how they loaded"), outputFileHtmlCon)
writeLines(paste0("    for(cc = 1;cc<controlChoices.length;cc=cc+1){"), outputFileHtmlCon)
writeLines(paste0("      cchoice=controlChoices[cc].labels[0].innerText;"), outputFileHtmlCon)
writeLines(paste0("      cchoice=cchoice.trim();"), outputFileHtmlCon) 
writeLines(paste0("      if(ro===cchoice){"), outputFileHtmlCon)
writeLines(paste0("        clickChoice(controlChoices[cc]);"), outputFileHtmlCon)
writeLines(paste0("      }"), outputFileHtmlCon)
writeLines(paste0("      if(ue===cchoice){"), outputFileHtmlCon)
writeLines(paste0("        clickChoice(controlChoices[cc]);"), outputFileHtmlCon)
writeLines(paste0("      }"), outputFileHtmlCon)
writeLines(paste0("    }"), outputFileHtmlCon)
writeLines(paste0("  }"), outputFileHtmlCon)
writeLines(paste0("}"), outputFileHtmlCon)

writeLines(paste0("</script>"), outputFileHtmlCon)

writeLines(paste0('<table>'), outputFileHtmlCon)
writeLines(paste0('<tr><td valign=top>'), outputFileHtmlCon)
writeLines(paste0('     <h3>Urban Extent Only Map</h3>'), outputFileHtmlCon)
writeLines(paste0('     <h3>Urban Extent: <div id="urbanExtentMapYear">All</div></h3>'), outputFileHtmlCon)
writeLines(paste0('     <input type="button" onClick="stepAnimate(1);" value="Animation - Forward in time."><br>'), outputFileHtmlCon)
writeLines(paste0('     <input type="button" onClick="stepAnimate(-1);" value="Animation - Backward in time."><br>'), outputFileHtmlCon)
writeLines(paste0('  </td>'), outputFileHtmlCon)
writeLines(paste0('  <td valign=bottom>'), outputFileHtmlCon)
writeLines(paste0('     <input type="button" onClick="unClickAll();" value="un-check all"><br>'), outputFileHtmlCon)
writeLines(paste0('     <input type="button" onClick="clickAll();" value="check all"><br>'), outputFileHtmlCon)
writeLines(paste0('  </td>'), outputFileHtmlCon)
writeLines(paste0('  <td valign=top>'), outputFileHtmlCon)
writeLines(paste0('     <h3>Rail Only Mass Transit Map</h3>'), outputFileHtmlCon)
writeLines(paste0('     <h3>Map year: <div id="mapYear">All</div></h3>'), outputFileHtmlCon)
writeLines(paste0('     <input type="button" onClick="stepAnimateRail(1);" value="Rail Animation - Forward in time."><br>'), outputFileHtmlCon)
writeLines(paste0('     <input type="button" onClick="stepAnimateRail(-1);" value="Rail Animation - Backward in time.">'), outputFileHtmlCon)
writeLines(paste0('</td></tr>'), outputFileHtmlCon)
writeLines(paste0('</table>'), outputFileHtmlCon)
writeLines(paste0('<p><div id="mapNotes"></div></p>'), outputFileHtmlCon)

genHTMLPageLinks(outputFileHtmlCon,pageLinks)

writeLines(paste0("<hr>"), outputFileHtmlCon)
genHTMLFootnotes(outputFileHtmlCon,9999)
genHTMLEndBody(outputFileHtmlCon)
close(outputFileHtmlCon)




#--------------------------------------------
# Major Changes
#--------------------------------------------

outputFileHtml <- paste0("C:\\a_orgs\\carleton\\hist3814\\R\\oc-transpo-maps-data\\output\\majorchanges.html")
outputFileHtmlCon<-file(outputFileHtml, open = "w")

genMapHTMLTop(outputFileHtmlCon, "Major Changes 1929-2015")
genMapHTMLScriptTop(outputFileHtmlCon, "Major Changes 1929-2015")

writeLines(paste0('  window.onload = function() {'), outputFileHtmlCon)
writeLines(paste0("    var basemap = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {"), outputFileHtmlCon)
writeLines(paste0("      attribution: '&copy; ",'<a href="http://osm.org/copyright">OpenStreetMap</a>',' contributors | <a href="https://library.carleton.ca/find/gis/geospatial-data/oc-transpo-transit-routes">MacOdrum Library</a>',"'"), outputFileHtmlCon)
writeLines(paste0("    });"), outputFileHtmlCon)
basemapTitle="Open Street Map Today"

genMapHTMLMapTop(outputFileHtmlCon)

genHTMLUrbanExtent(outputFileHtmlCon,1925)
genHTMLUrbanExtent(outputFileHtmlCon,1945)
genHTMLUrbanExtent(outputFileHtmlCon,1956)
genHTMLUrbanExtent(outputFileHtmlCon,1976)
genHTMLUrbanExtent(outputFileHtmlCon,1996)
genHTMLUrbanExtent(outputFileHtmlCon,2008)
genHTMLUrbanExtent(outputFileHtmlCon,2012)
genHTMLMajorChanges(outputFileHtmlCon,1929)
genHTMLMajorChanges(outputFileHtmlCon,1951)
genHTMLMajorChanges(outputFileHtmlCon,1962)
genHTMLMajorChanges(outputFileHtmlCon,1983)
genHTMLMajorChanges(outputFileHtmlCon,1986)
genHTMLMajorChanges(outputFileHtmlCon,1996)
#genHTMLMajorChanges(outputFileHtmlCon,2001)

writeLines(paste0("      controlLayers.addOverlay(basemap, '",basemapTitle,"');"), outputFileHtmlCon)
writeLines(paste0("      "), outputFileHtmlCon)
writeLines(paste0("  };"), outputFileHtmlCon)
writeLines(paste0(majorChangesJavaScriptObjects), outputFileHtmlCon)
writeLines(paste0(factsJavaScriptObjects), outputFileHtmlCon)
writeLines(paste0("var controlChoices=document.getElementsByClassName('leaflet-control-layers-selector');"), outputFileHtmlCon)
writeLines(paste0("var animLayer=0;"), outputFileHtmlCon)
writeLines(paste0("var animMajorChangesYear=-1;"), outputFileHtmlCon)

writeLines(paste0("// The years of urban growth data and their order."), outputFileHtmlCon)
writeLines(paste0("var urbanExtentYears = ["), outputFileHtmlCon)
writeLines(paste0("[1925, 1],"), outputFileHtmlCon)
writeLines(paste0("[1945, 2],"), outputFileHtmlCon)
writeLines(paste0("[1956, 3],"), outputFileHtmlCon)
writeLines(paste0("[1976, 4],"), outputFileHtmlCon)
writeLines(paste0("[1996, 5],"), outputFileHtmlCon)
writeLines(paste0("[2008, 6],"), outputFileHtmlCon)
writeLines(paste0("[2012, 7]"), outputFileHtmlCon)
writeLines(paste0("];"), outputFileHtmlCon)
writeLines(paste0("// The years of urban growth data may be out of order on the Leaflet control. "), outputFileHtmlCon)
writeLines(paste0("// Loop through the control, see where each year is and set the year's order in the list."), outputFileHtmlCon)
writeLines(paste0("function checkOrder(){"), outputFileHtmlCon)
writeLines(paste0("   controlChoices=document.getElementsByClassName('leaflet-control-layers-selector');"), outputFileHtmlCon)
writeLines(paste0("   for(cc2 = 0;cc2<urbanExtentYears.length;cc2=cc2+1){"), outputFileHtmlCon)
writeLines(paste0("      ue='Urban Extent '+urbanExtentYears[cc2][0];"), outputFileHtmlCon)
writeLines(paste0("      ue=ue.trim();"), outputFileHtmlCon)
writeLines(paste0("      for(cc = 1;cc<controlChoices.length;cc=cc+1){"), outputFileHtmlCon)
writeLines(paste0("         cchoice=controlChoices[cc].labels[0].innerText;"), outputFileHtmlCon)
writeLines(paste0("         cchoice=cchoice.trim();"), outputFileHtmlCon)
writeLines(paste0('         if(ue===cchoice){'), outputFileHtmlCon)
writeLines(paste0("            urbanExtentYears[cc2][1]=cc;"), outputFileHtmlCon)
writeLines(paste0("            cc=controlChoices.length;"), outputFileHtmlCon)
writeLines(paste0("         }"), outputFileHtmlCon)
writeLines(paste0("      }"), outputFileHtmlCon)
writeLines(paste0("   }"), outputFileHtmlCon)
writeLines(paste0("}"), outputFileHtmlCon)

genHTMLLeafletClickChoiceFunctions(outputFileHtmlCon,pageLinks)


writeLines(paste0("function stepAnimate(forward){"), outputFileHtmlCon)
writeLines(paste0("   controlChoices=document.getElementsByClassName('leaflet-control-layers-selector');"), outputFileHtmlCon)
writeLines(paste0("   unClickAll();"), outputFileHtmlCon)
writeLines(paste0("   checkOrder();"), outputFileHtmlCon)
writeLines(paste0("   animLayer=animLayer+forward;"), outputFileHtmlCon)	
writeLines(paste0("   if(animLayer>7){animLayer=1;}"), outputFileHtmlCon)
writeLines(paste0("   if(animLayer<1){animLayer=7;}"), outputFileHtmlCon)
writeLines(paste0("   clickChoice(controlChoices[urbanExtentYears[animLayer-1][1]]);"), outputFileHtmlCon)
writeLines(paste0('   document.getElementById("urbanExtentMapYear").innerHTML = urbanExtentYears[animLayer-1][0];'), outputFileHtmlCon)
writeLines(paste0("}"), outputFileHtmlCon)


writeLines(paste0("function stepAnimateMajorChanges(forward){"), outputFileHtmlCon)
writeLines(paste0("  controlChoices=document.getElementsByClassName('leaflet-control-layers-selector');"), outputFileHtmlCon)
writeLines(paste0("  unClickAll();"), outputFileHtmlCon)
writeLines(paste0("  animMajorChangesYear=animMajorChangesYear+forward;"), outputFileHtmlCon)
writeLines(paste0("  if(animMajorChangesYear>5){animMajorChangesYear=0;}"), outputFileHtmlCon)
writeLines(paste0("  if(animMajorChangesYear<0){animMajorChangesYear=5;}"), outputFileHtmlCon)

writeLines(paste0("  document.getElementById('mapYear').innerHTML = majorChanges[animMajorChangesYear].mapYear;"), outputFileHtmlCon)
writeLines(paste0('  if(typeof facts[majorChanges[animMajorChangesYear].mapYear] == "undefined"){'), outputFileHtmlCon)
writeLines(paste0("     document.getElementById('mapNotes').innerHTML = '';"), outputFileHtmlCon)
writeLines(paste0('   }else{'), outputFileHtmlCon)
writeLines(paste0("      document.getElementById('mapNotes').innerHTML = '<h3>Map Notes</h3>'+facts[majorChanges[animMajorChangesYear].mapYear]+'<hr>';"), outputFileHtmlCon)
writeLines(paste0('   }'), outputFileHtmlCon)  

writeLines(paste0("  document.getElementById('urbanExtentMapYear').innerHTML = majorChanges[animMajorChangesYear].geojsonUrbanGrowthYear;"), outputFileHtmlCon)
writeLines(paste0("  if(majorChanges[animMajorChangesYear].mapYear>=1929){"), outputFileHtmlCon)
writeLines(paste0("    ue='Urban Extent '+majorChanges[animMajorChangesYear].geojsonUrbanGrowthYear;"), outputFileHtmlCon)
writeLines(paste0("    ue=ue.trim();"), outputFileHtmlCon)
writeLines(paste0("    ro='';"), outputFileHtmlCon)
writeLines(paste0("    ro=majorChanges[animMajorChangesYear].geojsonMajorChangesYear+' All Routes';"), outputFileHtmlCon)
writeLines(paste0("    ro=ro.trim();"), outputFileHtmlCon)
writeLines(paste0("    // loop through the choices in the Leaflet control, they may be out of order, depending on how they loaded"), outputFileHtmlCon)
writeLines(paste0("    for(cc = 1;cc<controlChoices.length;cc=cc+1){"), outputFileHtmlCon)
writeLines(paste0("      cchoice=controlChoices[cc].labels[0].innerText;"), outputFileHtmlCon)
writeLines(paste0("      cchoice=cchoice.trim();"), outputFileHtmlCon) 
writeLines(paste0("      if(ro===cchoice){"), outputFileHtmlCon)
writeLines(paste0("        clickChoice(controlChoices[cc]);"), outputFileHtmlCon)
writeLines(paste0("      }"), outputFileHtmlCon)
writeLines(paste0("      if(ue===cchoice){"), outputFileHtmlCon)
writeLines(paste0("        clickChoice(controlChoices[cc]);"), outputFileHtmlCon)
writeLines(paste0("      }"), outputFileHtmlCon)
writeLines(paste0("    }"), outputFileHtmlCon)
writeLines(paste0("  }"), outputFileHtmlCon)
writeLines(paste0("}"), outputFileHtmlCon)

writeLines(paste0("</script>"), outputFileHtmlCon)

writeLines(paste0('<table>'), outputFileHtmlCon)
writeLines(paste0('<tr><td valign=top>'), outputFileHtmlCon)
writeLines(paste0('     <h3>Urban Extent Only Map</h3>'), outputFileHtmlCon)
writeLines(paste0('     <h3>Urban Extent: <div id="urbanExtentMapYear">All</div></h3>'), outputFileHtmlCon)
writeLines(paste0('     <input type="button" onClick="stepAnimate(1);" value="Animation - Forward in time."><br>'), outputFileHtmlCon)
writeLines(paste0('     <input type="button" onClick="stepAnimate(-1);" value="Animation - Backward in time."><br>'), outputFileHtmlCon)
writeLines(paste0('  </td>'), outputFileHtmlCon)
writeLines(paste0('  <td valign=bottom>'), outputFileHtmlCon)
writeLines(paste0('     <input type="button" onClick="unClickAll();" value="un-check all"><br>'), outputFileHtmlCon)
writeLines(paste0('     <input type="button" onClick="clickAll();" value="check all"><br>'), outputFileHtmlCon)
writeLines(paste0('  </td>'), outputFileHtmlCon)
writeLines(paste0('  <td valign=top>'), outputFileHtmlCon)
writeLines(paste0('     <h3>Major Changes in the Mass Transit Map</h3>'), outputFileHtmlCon)
writeLines(paste0('     <h3>Map year: <div id="mapYear">All</div></h3>'), outputFileHtmlCon)
writeLines(paste0('     <input type="button" onClick="stepAnimateMajorChanges(1);" value="Major Change Animation - Forward in time."><br>'), outputFileHtmlCon)
writeLines(paste0('     <input type="button" onClick="stepAnimateMajorChanges(-1);" value="Major Change Animation - Backward in time.">'), outputFileHtmlCon)
writeLines(paste0('</td></tr>'), outputFileHtmlCon)
writeLines(paste0('</table>'), outputFileHtmlCon)
writeLines(paste0('<p>'), outputFileHtmlCon)
writeLines(paste0('<p><div id="mapNotes"></div></p>'), outputFileHtmlCon)
writeLines(paste0('<p>This map takes more than a minute to load. When "1986 All Routes" appears in the map control panel in the top left of the map, loading is complete. '), outputFileHtmlCon)
writeLines(paste0(' Due to the loading time, this map is slow to operate. Click the button "Major Change Animation - Forward In Time" to see changes in the extent of the mass transit network.'), outputFileHtmlCon)
writeLines(paste0('</p>'), outputFileHtmlCon)
writeLines(paste0(''), outputFileHtmlCon)
writeLines(paste0('</p>'), outputFileHtmlCon)
writeLines(paste0('<p>'), outputFileHtmlCon)
writeLines(paste0(' A major change missing from this map is the O-Train in 2001.'), outputFileHtmlCon)
writeLines(paste0('</p>'), outputFileHtmlCon)
genHTMLPageLinks(outputFileHtmlCon,pageLinks)

writeLines(paste0("<hr>"), outputFileHtmlCon)
genHTMLFootnotes(outputFileHtmlCon,9999)
genHTMLEndBody(outputFileHtmlCon)
close(outputFileHtmlCon)



#--------------------------------------------
# index page
#--------------------------------------------

outputFileHtml <- paste0("C:\\a_orgs\\carleton\\hist3814\\R\\oc-transpo-maps-data\\output\\index.html")
outputFileHtmlCon<-file(outputFileHtml, open = "w")
genMapHTMLTop(outputFileHtmlCon, "Ottawa Mass Transit Routes 1929-2015")
writeLines(paste0("<h1>Ottawa Mass Transit Routes 1929-2015</h1>"), outputFileHtmlCon)
writeLines(paste0("<h3>Project</h3>"), outputFileHtmlCon)
writeLines(paste0("<p>This project is a series of maps of mass transit routes within the city of Ottawa 1929-2015. The maps are based on GIS files created and hosted at Carleton University's MacOdrum Library. Some historical topographical maps have been added to the earlier maps to provide context for the mass transit network as it existed at the time. To enable further analysis of mass transit routes additional data has been added. Maps display the boundary between urban and non-urban areas based on data from the National Capital Commission. The 1961 and 1971 Canadian Censuses have data of automobile ownership and that data is displayed on maps from 1962-1974.<p>"), outputFileHtmlCon)
writeLines(paste0('<p>This project was created for <a href="https://carleton.ca/history/people/john-c-walsh/">Dr. John Walsh&apos;s</a> Carleton University class <a href="https://carleton.ca/history/2019/mapping-course-offered-this-summer/">HIST 4303A: Maps and Mapping in Canadian History</a>.'), outputFileHtmlCon)
writeLines(paste0("<h3>Technology</h3>"), outputFileHtmlCon)
writeLines(paste0('<p>The programs to analyse the data and generate the maps are available on <a href="https://github.com/jeffblackadar/oc-transpo-maps/">github</a>.<p>'), outputFileHtmlCon)
writeLines(paste0("<h3>References</h3>"), outputFileHtmlCon)
writeLines(paste0('<p>This project would not exist without the datasets, maps, texts and tools noted in the <a href="references.pdf">references<a/>. Thank you to the creators and contributors who built these items.'), outputFileHtmlCon)
genHTMLPageLinks(outputFileHtmlCon,pageLinks)

writeLines(paste0("<hr>"), outputFileHtmlCon)
#genHTMLFootnotes(outputFileHtmlCon,generateYear)
genHTMLEndBody(outputFileHtmlCon)
close(outputFileHtmlCon)



#--------------------------------------------
# Timeline page
#--------------------------------------------
rmariadb.db<-"oc_transpo_maps"
routesDb<-dbConnect(RMariaDB::MariaDB(),default.file=rmariadb.settingsfile,group=rmariadb.db) 
outputFileHtml <- paste0("C:\\a_orgs\\carleton\\hist3814\\R\\oc-transpo-maps-data\\output\\timeline.html")
outputFileHtmlCon<-file(outputFileHtml, open = "w")
genMapHTMLTop(outputFileHtmlCon, "Ottawa Mass Transit Routes Timeline 1929-2015")
writeLines(paste0("<h1>Ottawa Mass Transit Routes Timeline 1929-2015</h1>"), outputFileHtmlCon)
writeLines(paste0('<table>'), outputFileHtmlCon)
writeLines(paste0("<tr><td><span style='text-align:left'><p>Year - Note</p></span></td><td><p>Map</p></td></tr>"), outputFileHtmlCon)
output_query_facts<-paste0("SELECT fact,footnote_number,fact_year,fact_map_year_start,fact_map_year_end FROM oc_transpo_maps.tbl_facts WHERE true ORDER BY fact_map_year_start, fact_year;")
output_rs_facts = dbSendQuery(routesDb,output_query_facts)
output_dbRows_facts<-dbFetch(output_rs_facts, 999999)
if (nrow(output_dbRows_facts)==0){
  print (paste0("Zero rows for timeline"))
  dbHasCompleted(output_rs_facts)
  dbClearResult(output_rs_facts)
} else {
  timeLineYear=0
  timeLineMapYear=0
  for (i_facts in 1:nrow(output_dbRows_facts)) {
    if(timeLineMapYear!=output_dbRows_facts[i_facts, 4]){
      if(timeLineMapYear==0){
        writeLines(paste0("<tr><td><span style='text-align:left'>"), outputFileHtmlCon)
      }else{
        writeLines(paste0('</span></ul></td><td><a href="',timeLineMapYear,'.html">',timeLineMapYear," Map</a></td></tr><tr><td align='left'><span style='text-align:left'>"), outputFileHtmlCon)
      }
    }
    timeLineMapYear=output_dbRows_facts[i_facts, 4]
    if(timeLineYear!=output_dbRows_facts[i_facts, 3]){
      writeLines(paste0("</ul><p><b>",output_dbRows_facts[i_facts, 3],":</b></p><ul><span style='text-align:left'>"), outputFileHtmlCon)
    }
    timeLineYear=output_dbRows_facts[i_facts, 3]
    writeLines(paste0("<li><p>",output_dbRows_facts[i_facts, 1],' <a href="#footnote',output_dbRows_facts[i_facts, 2],'"><sup>',output_dbRows_facts[i_facts, 2],'</sup></a></p></li>'), outputFileHtmlCon)
  }
  writeLines(paste0('</span></ul></td><td><a href="',timeLineMapYear,'.html">',timeLineMapYear," Map</a></td></tr>"), outputFileHtmlCon)
  dbHasCompleted(output_rs_facts)
  dbClearResult(output_rs_facts)
}
writeLines(paste0('</table>'), outputFileHtmlCon)
genHTMLPageLinks(outputFileHtmlCon,pageLinks)
writeLines(paste0("<hr>"), outputFileHtmlCon)
genHTMLFootnotes(outputFileHtmlCon,9999)
genHTMLEndBody(outputFileHtmlCon)
close(outputFileHtmlCon)
dbDisconnect(routesDb)
